      <div id="abstract">
        <h2>Abstract</h2>

        <blockquote>
          <p>“ECMAScript is a standard for object-oriented programming languages.
             Superficially, its implementations, like JavaScript and JScript,
             are very similar. They are therefore often discussed in a
             simplified way. But does this approach hold water against
             methodical testing?</p>

          <p>In this work, features of ECMAScript and its common
             implementations are compared with regard to their standards
             compliance and compatibility. A web application is created
             for the registration of features and associated test cases.
             Using this application, the test cases are run in web browsers
             and the test results are stored in a database. The results
             are correlated with the market share of the used web browsers
             and their degree of vendor support. Thus, features can be
             defined as safe for use in web browsers, which makes
             efficiency-reducing compatibility measures unnecessary.”<?php
           echo $this->footnotes->add('abstract', null,
               'Lahn,&nbsp;Thomas (2012-03-12). <i><a href="application/doc/thesis.pdf"
               >Features von ECMAScript-basierten Programmiersprachen&nbsp;–
               Eine vergleichende Analyse</a> (“Features of ECMAScript-based
               programming languages&nbsp;– A&nbsp;comparative analysis”)</i>
               <em>(revised)</em>. <abbr title="Bachelor of Science"
               >BSc</abbr>&nbsp;<a href="http://www.supsi.ch/home_en.html"><abbr
               title="Scuola universitaria professionale della Svizzera italiana"
               >SUPSI</abbr></a> in Computer Science. <a href="http://www.ffhs.ch/"
               >Fernfachhochschule Schweiz</a> (Swiss Distance
               University of Applied&nbsp;Sciences).', ''); ?></p>
        </blockquote>
      </div>