      <div>
        <h2><a name="contributors" id="contributors">List of Contributors</a></h2>

        <div><a href="#toc">&#8593; Table of contents</a></div>

        <p><em>Thanks to (in alphabetical order):</em></p>
      </div>

      <ul>
        <li><a href="http://asenbozhilov.com/">Asen Bozhilov
          (<span lang="bg">Асен Божилов</span>)</a>
          &lt;<a href="<?php echo randomEsc('mailto:asen.bozhilov@gmail.com'); ?>"
          ><?php echo randomEsc('asen.bozhilov@gmail.com'); ?></a>&gt;
          for corrections on ECMAScript Editions and feature suggestions</li>
        <li>BootNic &lt;<a href="<?php echo randomEsc('mailto:bootnic.bounce@gmail.com'); ?>"
          ><?php echo randomEsc('bootnic.bounce@gmail.com'); ?></a>&gt;
          for helping with the scrollable tbody workaround for IE: Message-ID&nbsp;<a
          href="http://groups.google.com/groups/search?as_umsgid=20100305112229.454328ac@bootnic.eternal-september.org"
          >&lt;20100305112229.454328ac@bootnic.eternal-september.org&gt;</a></li>
        <li><a href="http://perfectionkills.com/">Juriy&nbsp;'kangax'&nbsp;Zaytsev
          (<span lang="ru">Юрий Зайцев</span>)</a>
          &lt;<a href="<?php echo randomEsc('mailto:kangax@gmail.com'); ?>"
          ><?php echo randomEsc('kangax@gmail.com'); ?></a>&gt;
          for tests with Safari&nbsp;2.0.2: Message-ID&nbsp;<a
          href="http://groups.google.com/groups/search?as_umsgid=MpOdnVEQCfgNMN_WnZ2dnUVZ_rNi4p2d@giganews.com"
          >&lt;MpOdnVEQCfgNMN_WnZ2dnUVZ_rNi4p2d@giganews.com&gt;</a></li>
        <li>Michael&nbsp;Winter
          &lt;<a href="<?php echo randomEsc('mailto:m.winter@blueyonder.co.uk'); ?>"
          ><?php echo randomEsc('m.winter@blueyonder.co.uk'); ?></a>&gt;
          for tests with IE&nbsp;4.01 and NN&nbsp;4.08: Message-ID&nbsp;<a
          href="http://groups.google.com/groups/search?as_umsgid=urctf.17012$iz3.5930@text.news.blueyonder.co.uk"
          >&lt;urctf.17012$iz3.5930@text.news.blueyonder.co.uk&gt;</a></li>
      </ul>