          <tr>
<?php
$scriptEngineTest = <<<HTML
                  <ul>
                    <li>This user agent:
                      <script type="text/javascript">
                        document.write('<p><b>' + navigator.userAgent + '<\/b><\/p>');
                      </script>
                      <noscript>
                        <p><b>{$_SERVER['HTTP_USER_AGENT']}</b></p>
                      </noscript>
                    </li>

                    <li><a name="script-engine-test" id="script-engine-test"
                      >This ECMAScript implementation</a><script type="text/javascript"
                         src="application/scripts/version-detection.js"></script>
                    </li>
                  </ul>
HTML;

if ($this->edit)
{
  ?>
            <td style="width: 7em">&nbsp;</td>
<?php
  }
?>
            <th id="hdr-feature" data-title="Feature">
<?php
  if ($this->edit)
  {
?>
              <a href="<?php echo $this->escape($this->getURL('feature', 'add')); ?>"
                 title="Add feature"
                 class="add">Add</a>
<?php
  }
?>
              <label for="filter"><u>F</u>eature</label> <script type="text/javascript">
              printScrollButton();
            </script>
            <div title="Go to the first entry that begins with the selected character" style="border-bottom: none"
                 ><a href="#!">!</a>
              <?php
                for ($i = ord('a'), $max = ord('z'); $i <= $max; $i++)
                {
                  $s = chr($i);
                  echo '<a href="#' . $s . '">' . strtoupper($s) . '</a> ';
                }
                ?></div>
            <div>
              <script type="text/javascript" src="../../builder?src=regexp,dom/timeout"></script>
              <input type="search" name="filter" id="filter" accesskey="f" style="width: 100%"
                     onkeyup="es_matrix.timeout.run()"
                     oninput="es_matrix.timeout.run()"
                     placeholder="Filter expression (shortcut: Access Key + F)"
                     title="Expression to filter the feature table (shortcut: Access Key + F)">
              </div>
            </th>
            <th id="hdr-es" title="ECMAScript Edition"><a href="#ecmascript">ECMAScript</a></th>
            <th id="hdr-this" data-title="This implementation">This <abbr title="implementation">impl.</abbr><?php
                echo $this->footnotes->add('this-impl', null, $scriptEngineTest, '');
                ?><br>
              <script type="text/javascript" src="application/scripts/impl-detection.js"></script>
<?php
  if (/*$_SERVER['HTTP_HOST'] === 'localhost' && */!$this->edit)
  {
?>
              <button type="submit" name="action" value="saveResults" accesskey="s"
                      title="Submit test results (Shortcut: Access Key + S)"
                      ><u>S</u>ubmit results</button></th>
<?php
  }

  $implementations = $this->implementations;
  foreach ($implementations as $impl)
  {
?>
            <th id="hdr-<?php
              echo $this->escape(
                strtolower(
                  ($impl->acronym !== '')
                    ? strtolower($impl->acronym)
                    : $impl->name
                )
              );
              ?>"><?php
              if ($impl->acronym !== '')
              {
                ?><abbr title="<?php echo $this->escape($impl->name); ?>"><?php
                echo $this->escape($impl->acronym);
              }
              else
            {
                echo $this->escape($impl->name);
              }

              if ($impl->acronym !== '')
              {
                ?></abbr><?php
              }

              if ($this->edit)
              {
                ?><br>
                <a href="<?php echo $this->escape($this->getURL('implementation', 'edit', $impl->id)); ?>"
                   class="edit">Edit</a><?php
              }
            ?></th>
<?php
  }

  if ($this->edit)
  {
?>
            <td><a href="<?php echo $this->escape($this->getURL('implementation', 'add')); ?>"
                   title="Add implementation"
                   class="add">Add</a></td>
<?php
  }
?>
          </tr>
