          <tr>
<?php
$scriptEngineTest = <<<HTML
                  <ul>
                    <li>This user agent:
                      <script type="text/javascript">
                        document.write('<p><b>' + navigator.userAgent + '<\/b><\/p>');
                      </script>
                      <noscript>
                        <p><b>{$_SERVER['HTTP_USER_AGENT']}</b></p>
                      </noscript>
                    </li>

                    <li><a name="script-engine-test" id="script-engine-test"
                      >This ECMAScript implementation</a><script type="text/javascript"
                         src="application/scripts/version-detection.js"></script>
                    </li>
                  </ul>
HTML;

if ($this->edit)
{
  ?>
            <td style="width: 7em">&nbsp;</td>
<?php
  }
?>
            <th id="hdr-feature">
<?php
  if ($this->edit)
  {
?>
              <a href="<?php echo $this->escape($this->getURL('feature', 'add')); ?>"
                 title="Add feature"
                 class="add">Add</a>
<?php
  }
?>
              <label for="filter"><u>F</u>eature</label> <script type="text/javascript">
              printScrollButton();
            </script>
            <div title="Go to the first entry that begins with the selected character" style="border-bottom: none"
                 ><a href="#!">!</a>
              <?php
                for ($i = ord('a'), $max = ord('z'); $i <= $max; $i++)
                {
                  $s = chr($i);
                  echo '<a href="#' . $s . '">' . strtoupper($s) . '</a> ';
                }
                ?></div>
            <div>
              <script type="text/javascript" src="../../builder?src=regexp,dom/timeout"></script>
              <input type="search" name="filter" id="filter" accesskey="f" style="width: 100%"
                     onkeyup="es_matrix.timeout.run()"
                     oninput="es_matrix.timeout.run()"
                     placeholder="Filter expression (shortcut: Access Key + F)"
                     title="Expression to filter the feature table (shortcut: Access Key + F)">
              </div>
            </th>
            <th id="hdr-es"><a href="#ecmascript">ECMAScript</a></th>
            <th id="hdr-this">This <abbr title="implementation">impl.</abbr><?php
                echo $this->footnotes->add('this-impl', null, $scriptEngineTest, '');
                ?><br>
              <script type="text/javascript">
                function strReplace (needle, replacement, haystack, global)
                {
                  var i,
                      lastIndex = 0,
                      replacementLen = replacement.length;

                  while ((i = haystack.indexOf(needle, lastIndex)) > -1)
                  {
                    haystack = haystack.substring(0, i)
                             + replacement
                             + haystack.substring(i + replacementLen);
                    if (!global)
                    {
                      break;
                    }

                    lastIndex = i + replacementLen;
                  }

                  return haystack;
                }

                var implementation = jsx.object.isMethod(this, "ScriptEngine") ? ScriptEngine() : '';
                if (implementation)
                {
                  implementation = strReplace("<", "&gt;", strReplace('"', "&quot;", implementation, true), true);
                  var version = '';
                  if (jsx.object.isMethod(this, "ScriptEngineMajorVersion"))
                  {
                    version = ScriptEngineMajorVersion();

                    if (jsx.object.isMethod(this, "ScriptEngineMinorVersion"))
                    {
                      version += "." + ScriptEngineMinorVersion();

                      if (jsx.object.isMethod(this, "ScriptEngineBuildVersion"))
                      {
                        version += "." + ScriptEngineBuildVersion();
                      }
                    }

                    if (version)
                    {
                      version = strReplace("<", "&gt;", strReplace('"', "&quot;", version, true), true);
                    }
                  }

                  document.write(
                    '<input type="hidden" name="implementation" value="' + implementation + '">'
                    + '<input type="hidden" name="version" value="' + version + '">');
                }
              </script>
<?php
  if (/*$_SERVER['HTTP_HOST'] === 'localhost' && */!$this->edit)
  {
?>
              <button type="submit" name="action" value="saveResults" accesskey="s"
                      title="Submit test results (Shortcut: Access Key + S)"
                      ><u>S</u>ubmit results</button></th>
<?php
  }

  $implementations = $this->implementations;
  foreach ($implementations as $impl)
  {
?>
            <th id="hdr-<?php
              echo $this->escape(
                strtolower(
                  ($impl->acronym !== '')
                    ? strtolower($impl->acronym)
                    : $impl->name
                )
              );
              ?>"><?php
              if ($impl->acronym !== '')
              {
                ?><abbr title="<?php echo $this->escape($impl->name); ?>"><?php
                echo $this->escape($impl->acronym);
              }
              else
            {
                echo $this->escape($impl->name);
              }

              if ($impl->acronym !== '')
              {
                ?></abbr><?php
              }

              if ($this->edit)
              {
                ?><br>
                <a href="<?php echo $this->escape($this->getURL('implementation', 'edit', $impl->id)); ?>"
                   class="edit">Edit</a><?php
              }
            ?></th>
<?php
  }

  if ($this->edit)
  {
?>
            <td><a href="<?php echo $this->escape($this->getURL('implementation', 'add')); ?>"
                   title="Add implementation"
                   class="add">Add</a></td>
<?php
  }
?>
          </tr>
