<?php
  if (!$this->edit)
  {
?>
    <section>
      <div id="abstract">
        <h2>Abstract</h2>

        <blockquote>
          <p>“ECMAScript is a standard for object-oriented programming languages.
             Superficially, its implementations, like JavaScript and JScript,
             are very similar. They are therefore often discussed in a
             simplified way. But does this approach hold water against
             methodical testing?</p>

          <p>In this work, features of ECMAScript and its common
             implementations are compared with regard to their standards
             compliance and compatibility. A web application is created
             for the registration of features and associated test cases.
             Using this application, the test cases are run in web browsers
             and the test results are stored in a database. The results
             are correlated with the market share of the used web browsers
             and their degree of vendor support. Thus, features can be
             defined as safe for use in web browsers, which makes
             efficiency-reducing compatibility measures unnecessary.”<?php
           echo $this->footnotes->add('abstract', null,
               'Lahn,&nbsp;Thomas (2012-03-12). <i>Features von
               ECMAScript-basierten Programmiersprachen – Eine vergleichende
               Analyse (“Features of ECMAScript-based
               programming languages – A&nbsp;comparative analysis”)</i>
               <em>(revised)</em>. <abbr title="Bachelor of Science"
               >BSc</abbr>&nbsp;<a href="http://www.supsi.ch/"><abbr
               title="Scuola universitaria professionale della Svizzera italiana"
               >SUPSI</abbr></a> in Computer Science. <a href="http://www.ffhs.ch/"
               >Fernfachhochschule Schweiz</a> (Swiss Distance
               University of Applied&nbsp;Sciences).', ''); ?></p>
        </blockquote>
      </div>
    </section>

    <section>
      <div id="foreword">
        <h2>Foreword and Rationale</h2>

<!--         <div> -->
          <div><a href="#toc">&#8593; Table of contents</a></div>

<!--           <ul> -->
<!--             <li><a href="#not-the-same">The same, but not the same</a></li> -->
<!--             <li><a href="#about">What is the Matrix?</a></li> -->
<!--             <li><a href="#reloaded">Reloaded</a></li> -->
<!--           </ul> -->
<!--         </div> -->

        <section>
          <blockquote>
            <p style="margin-bottom: 0; font-style: italic"
               ><!--<span lang="x-vulcan">&gt;Oren'uh pa'shi-nahpau.
                Oren'uh fai-tukh t'natyan — nam-tor vellar heh ri nam-tor.&lt;</span><br>
                (-->“Learn to think clearly.
                Learn to distinguish: what is, and what seems to be.”<!--)--></p>
            <div style="text-align: right"> —&nbsp;Surak<?php
    //              echo $this->footnotes->add('vli', null, 'see also:
    //                <a href="http://stogeek.com/wiki/Category:Vulcan_Language_Institute"
    //                   >Vulcan Language Institute</a>', ''); ?></div>
          </blockquote>

          <p>In a discussion, especially a technical one, it is very
             important that all participants know what is being talked
             about, so that misunderstandings can be avoided.  <em>Clear
             language</em> is required.  It can be achieved only by
             using terms that are <em>well-defined</em>; they should be
             unambiguous and one should be able to look them up
             in official reference material.</p>

          <p>Some people talk about a programming language they call
             “javascript”.  This is supposed to be one fully specified
             and universally implemented programming language that
             provides, in dialects to a varying degree, the
             capabilities to manipulate runtime environments such as
             web browsers.</p>

          <p>In fact, <strong>there is no “javascript”</strong>;
             there is <em>JavaScript</em>.  This is not just
             a matter of letter case: JavaScript is the name
             of <em>one</em> implementation of a standard for
             extensible scripting languages, <em>ECMAScript</em>.</p>

          <p>“A <em>scripting language</em> is a programming language
             that is used to manipulate, customise, and automate
             the facilities of an existing system.”<?php
               echo $this->footnotes->add('es5.1', null,
                 'Ecma&nbsp;International (2011&#8209;06).
                  <a href="http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf"
                     ><i>Standard ECMA&#8210;262. ECMAScript Language Specification.</i>
                      5.1 Edition.</a> (retrieved 2011&#8209;08&#8209;27)')
             ?>  The <em>ECMAScript Language Specification</em>
             is a standard for scripting languages.  It is published
             in <em>Editions</em>.
             Several current versions of scripting languages
             are implementations of an Edition of ECMAScript.
             But its first Edition was based itself on two scripting
             languages that were already implemented for use in
             web browsers: Netscape JavaScript 1.1 and Microsoft
             JScript 1.0.<?php
               echo $this->footnotes->add('es1', null,
                 'Ecma&nbsp;International (1997-06).
                  <a href="http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf"
                     ><i>ECMAScript Language Specification (1st edition)</i></a> (retrieved 2012&#8209;12&#8209;10)')
             ?></p>

          <p><strong>There are no dialects of “javascript”</strong>;
             there are <em>several implementations of ECMAScript</em>
             that are widely distributed, primarily through web browsers.
             The features that allow one to manipulate web browsers
             are <em>not</em> part of any such programming language;
             they are environment-dependent implementations of
             language-independent
             <abbr title="API: Application Programming Interface">API</abbr>s
             for which a <em>language binding</em> is specified <?php
               echo $this->footnotes->add('binding', null,
                 'See <a href="http://www.w3.org/TR/2003/REC-DOM-Level-2-HTML-20030109/ecma-script-binding.html"
                  >W3C DOM Level 2 HTML</a> for an example of language binding.');
             ?> so that they can
             be used with that programming language.<?php
               echo $this->footnotes->add('legacy', null,
                 'The distinction between core language and browser API
                  was not made in Netscape JavaScript before version 1.4.
                  JavaScript was designed to be the programming language
                  for scripts in Netscape Navigator, therefore the
                  Netscape API was part of JavaScript. This changed
                  when JavaScript needed to work server-side in
                  Netscape Enterprise Server as well.');
            ?></p>
        </section>

        <section>
          <h3 id="#not-the-same">The same, but not the same</h3>

          <p>Superficially, ECMAScript implementations are very similar.
             It is therefore tempting to discuss them in a simplified way
             using an umbrella term such as “javascript”.<?php
               echo $this->footnotes->add('cljs-FAQ', null,
                 '<a href="http://jibbering.com/faq/">comp.lang.javascript FAQ</a>');
             ?> But this approach is not without problems.
             ECMAScript gives its conforming implementations a wide latitude.
             The Editions of ECMAScript and their implementations
             <a href="#timeline">have been developed in parallel,
             and are partially informing each other</a>.  Also,
             some implementations are not conforming in some features.
             As a result, ECMAScript implementations are in fact
             very different from one another.</p>

          <p>It does matter which implementation is being discussed.
             Using ambiguous umbrella terms, without providing a
             clear definition for them, cannot be considered
             appropriate style in a technical discussion.</p>

          <p>Hence, for lack of a better alternative, the precise
             and equally concise term <strong>ECMAScript implementation(s)</strong>
             should be used when talking about features that several
             implementations (ought to) have in common (per
             the ECMAScript Language Specification).  And whenever
             it was talked about one particular implementation, its proper
             name should be used, like <strong>Netscape/Mozilla.org JavaScript</strong>
             or simply <strong>JavaScript</strong> (if there is doubt,
             "™" might be added to emphasize that the implementation
             is meant).  <strong>In all other instances, the term
             “JavaScript” (in any letter case) should <em>not</em>
             be used.</strong></p>
        </section>

        <section>
          <h3 id="about">What is the Matrix?</h3>

          <p>This overview&nbsp;– the <em>ECMAScript Support Matrix</em> –
             began as a comparison of different “JavaScript” features and,
             as time passed and understanding grew, evolved into a comparison
             between the major ECMAScript implementations, detailing
             the differences, the quirks and the bugs.  It has been serving
             its author (and its dedicated readers) for years in writing
             client-side scripts that work cross-browser, and has been helping
             to see the distinction between core language features, and APIs
             with language binding, like the DOM.  (The features of the latter
             API will be compared in another Matrix.)</p>

          <p>Whenever you read from this author that key line from arguably
             <a href="http://en.wikipedia.org/wiki/The_Matrix"
                title="The Matrix movie on Wikipedia"
                >the most groundbreaking hacker movie</a>
             &#8213;“The Matrix has you!”&#8213; a suggestion
             is being considered as a
             <a href="#contributors">contribution</a> to this work.
             See below.</p>
        </section>

        <section>
          <h3 id="reloaded">Reloaded</h3>

          <p>Despite several valuable contributions, the previous version
             of this work has primarily suffered from the fact that most
             language features could only be tested, and test results
             documented, as far as the resources of its author permitted.
             Furthermore, it was not possible without considerable effort
             to detail the differences between versions of the same
             implementation. Test cases were incomplete and sketchy
             at best.</p>

          <p>This version is based on a novel, scientific
             approach<?php echo $this->footnotes->add('abstract'); ?>,
             with which features can be tested by <em>anyone</em>
             in the runtime environments available to them, and those
             test results can be fed back to the overview <em>immediately</em>,
             detailing <em>automatically</em> the differences between
             the implementations and the versions of the same
             implementation.  <!-- Whenever possible, test cases
             are designed as tests against a reference implementation
             of ECMAScript written in ECMAScript, in order to reduce
             the number of possible false negatives and false
             positives. --></p>

          <p>As a result, the general recommendation
             as to whether a feature can be considered <em>safe</em>
             (see below) can be updated immediately and semi-automatically
             as well.  This is assumed to further improve the overall
             quality of design decisions with regard to language features
             (although the caveat as to that must stay in place).</p>

          <p class="status"><em>This is a work in progress.  The feedback
             feature has been disabled for the time being to ensure
             the integrity of the already obtained results.  You are
             kindly requested to postpone your contributions until it
             is released.</em></p>
        </div>
      </section>
    </section>

    <section>
      <div id="features">
        <h2>Language&nbsp;Features</h2>

        <div>
          <div><a href="#toc">&#8593; Table of contents</a></div>

          <ul>
            <li><a href="#type-hinting">Notes on type hinting</a></li>
            <li><a href="#features-table">List of features</a></li>
          </ul>
        </div>

        <p><a href="#features-table">The following table</a> lists features
          of ECMAScript and its implementations, with the Edition or version
          that introduced it; furthermore, information about features that
          have been deprecated is included.</p>

        <p>Features are <span class="safe"><span class="visual">highlighted
          with a greenish background color</span></span> if they can be
          considered <em>safe</em> to use without prior feature test
          even when they do not appear to be formally specified or
          to be supported among all versions of all implementations
          considered here.  This is based on the fact that all minimum
          versions of the implementations that a&nbsp;feature
          requires can be considered obsolete because the user&nbsp;agents
          known to implement them can be considered obsolete (see the
          respective <a href="#version-info">version information</a>
          for details).  Note that this assessment is likely to be
          subject to change as more implementations are investigated.
          If taken as a&nbsp;recommendation for design decisions,
          it should be taken as a light&nbsp;one.</p>

        <p><strong>The contents of <a href="#features-table">this table</a>
          are based on what could be found in the Editions of ECMAScript
          and in vendor's online documentation to date.  They are
          completed with results from test cases that have been run in a
          careful selection of <a href="#environments">host environments</a>,
          <em>and do not claim to be accurate or complete</em>.  Any
          correction/addition as to how things really are is welcome and will be
          <a href="#contributors">credited</a> where it is due.</strong></p>

        <section>
          <h3 id="type-hinting">Notes on type hinting</h3>

          <p>The ECMAScript type system has grown quite complex
             which makes it difficult to document features properly:</p>

          <figure>
            <ul class="tree">
              <li><code>Object</code>
                <ul>
                  <li><code>Array</code></li>
                  <li><code>Boolean</code>
                   <ul>
                     <li><code>boolean</code></li>
                   </ul></li>
                  <li><code>Date</code></li>
                  <li><code>Function</code></li>
                  <li><code>Number</code>
                    <ul>
                      <li><code>byte</code> (ES&thinsp;4)</li>
                      <li><code>double</code> (ES&thinsp;4)</li>
                      <li><code>float</code> (ES&thinsp;4)</li>
                      <li><code>int</code> (ES&thinsp;4)</li>
                      <li><code>number</code> (ES&thinsp;3)</li>
                      <li><code>uint</code> (ES&thinsp;4)</li>
                    </ul>
                  </li>
                  <li><code>RegExp</code> (ES&thinsp;3)</li>
                  <li><code>String</code>
                    <ul>
                      <li><code>string</code></li>
                    </ul></li>
                </ul></li>
              <li><code>Null</code>
              <li><code>Undefined</code>
            </ul>
            <figcaption>ECMAScript type system by inheritance
              and wrapper type relation</figcaption>
          </figure>

          <p>There are primitive values and object values.  Especially,
             in addition to <code>Object</code>, for each primitive
             value except <code>null</code> and <code>undefined</code>
             there is an object value wrapping it if necessary.
             However, those wrapper values exhibit unintuitive
             behavior and should be avoided<sup>[citation needed]</sup>.  Because the wrapper
             values are object values instead of primitive values,
             they can be said to be of another type than the wrapped
             primitive value; for the purposes of disambiguation,
             henceforth <code>string</code> will be used for the
             the primitive type, and <code>String</code> for the
             object type.<br>
             Values of the wrapper types do not need to be created
             explicitly, because they are created implicitly if
             necessary: <code>Math.PI.toString(2)</code> is
             equivalent to <code>(new Number(Math.PI)).toString(2)</code>,
             although <code>Math.PI</code> holds a primitive value
             of type <code>number</code>.
             Regardless, while user code would have to take special
             precautions to handle those differences, ECMAScript
             algorithms handle those seamlessly with the internal
             <code>Type</code> algorithm<sup>[citation needed]</sup>. But they never return
             values of wrapper object types.  Therefore, for
             example parameters are hinted as <code>String</code>,
             while return values are hinted as <code>string</code>,
             even though the algorithm of the function converts all
             arguments where <code>String</code> is hinted,
             to a primitive <code>string</code> value (using the
             <code>ToString</code> algorithm).</p>

          <p><code>Null</code> is a primitive type with the sole
             value <code>null</code>.  However, because <code>null</code>
             is in Edition 5.1 a “primitive value that represents
             the intentional absence of any object value”, and
             in Edition 3 Final “a primitive value that represents
             the null, empty, or non-existent reference”, sometimes
             <code>null</code> can be used where object types are
             expected (one can assume that this is the rationale
             for <code>typeof null</code> evaluating to
             <code>"object"</code>).  Therefore, it makes sense
             to classify values that can be either of a type other
             than <code>Null</code> or <code>null</code> as values
             of a <a href="http://www.w3.org/TR/WebIDL/#idl-nullable-type"
                     title="WebIDL: Nullable types"><em>nullable type</em></a>.</p>

          <p>Implementations of ECMAScript Editions 1 to 3, 5,
             and beyond, support only <a href="http://en.wikipedia.org/wiki/Dynamic_typing"
             >dynamic</a> and <a href="http://en.wikipedia.org/wiki/Type_system#Strong_and_weak_typing"
             >weak typing</a>; there is only one numerical type,
             <code>Number</code>, implementing IEEE-754 “double precision”
             floating-point values.  Implementations of the proposal
             for ECMAScript Edition&nbsp;4, however, also support
             <a href="http://en.wikipedia.org/wiki/Static_typing"
             >static</a> and <a href="http://en.wikipedia.org/wiki/Type_system#Strong_and_weak_typing"
             >strong typing</a>; for that, there are also specific
             numerical types like <code>int</code> and
             <code>double</code>.</p>

          <p>Sometimes a method may also accept values of any type,
             or return a value of a type depending on the arguments.
             In this case, the parameter or return value is hinted
             to be of type <code>any</code>.</p>

          <p>The following special types have been used for
             type hinting here:</p>

          <table>
            <thead>
              <tr>
                <th>Type</th>
                <th>Meaning</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th><code>any</code></th>
                <td>All values are supported, or the method returns
                    a value of a type depending on its input.</td>
              </tr>
              <tr>
                <th><code><var>any</var>?</code></th>
                <td>Nullable type.  Supported values include those
                    of type <code><var>any</var></code>, and
                    <code>null</code>.</td>
              </tr>
              <tr>
                <th><code>double</code></th>
                <td>“Double precision” floating-point value.
                    <code>double</code> for supporting implementations,
                    <code>Number</code> (for parameters) or
                    <code>number</code> (for return values) otherwise.</td>
              </tr>
              <tr>
                <th><code>float</code></th>
                <td>“Single precision” floating-point value.
                    <code>float</code> for supporting implementations,
                    <code>Number</code> (for parameters) or
                    <code>number</code> (for return values) otherwise.</td>
              </tr>
              <tr>
                <th><code>int</code></th>
                <td>Integer value or floating-point value with zero
                    fractional part.  <code>int</code> for supporting
                    implementations, <code>Number</code> (for parameters)
                    or <code>number</code> (for return values) otherwise.</td>
              </tr>
            </tbody>
          </table>

          <p>On the other hand, each object can be associated with
             a constructor, because the constructor has a prototype
             property that serves as an object's <em>prototype
             object</em> for property resolution along the
             <em>prototype chain</em>.  For internal object types,
             the constructor also defines the value of the internal
             <code>[[Class]]</code> property.  <em>This must not be
             confused with class-based inheritance.</em>  However, it
             is useful to hint the expected type by the constructor
             that should have been used to create the value,
             to point out the properties required on an object for
             which a reference is passed, or to which a reference
             is returned.</p>
        </section>
      </div>
<?php
    if ($_SERVER['HTTP_HOST'] === 'localhost')
    {
      ?><a href="<?php echo $this->escape($this->getURL(null, 'edit')); ?>">Edit</a><?php
    }
  }
  else
  {
?>
     <a href="<?php echo $this->escape($this->getURL(null, 'endEdit')); ?>">End Edit</a>
<?php
  }

  if (!$this->edit)
  {
?>
      <form action="<?php echo $this->escape($this->getURL()); ?>" method="POST">
<?php
  }
?>
        <table id="features-table"
               onclick="table_click(typeof event != 'undefined' ? event : void 0)">
          <caption>
            Language features
          </caption>
          <thead>
            <?php require_once 'features-head.phtml'; ?>
          </thead>
          <tfoot>
            <?php require_once 'env-list.phtml'; ?>
          </tfoot>
          <tbody id="scroller" class="scroll">
            <?php require_once 'features-list.phtml'; ?>
          </tbody>
        </table>
<?php
  if (!$this->edit)
  {
?>
      </form>
<?php
  }

  $this->footnotes->flush();
?>
    </section>

    <section>
      <div>
        <h2><a name="version-info" id="version-info">Version Information</a></h2>

        <div><a href="#toc">&#8593; Table of contents</a></div>

        <ul>
          <li><a href="#timeline">Timeline</a></li>
          <li><a href="#javascript">Netscape/Mozilla.org JavaScript</a></li>
          <li><a href="#jscript">Microsoft JScript</a></li>
          <li><a href="#v8">Google V8</a></li>
          <li><a href="#jsc">Apple JavaScriptCore</a></li>
          <li><a href="#opera">Opera ECMAScript</a></li>
          <li><a href="#actionscript">Adobe ActionScript</a></li>
          <li><a href="#ecmascript">ECMAScript compatibility</a></li>
        </ul>
      </div>

      <section>
        <div>
          <h3><a name="timeline" id="timeline">Timeline</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <figure style="margin-left: 0; margin-right: 0">
          <a href="application/layouts/index/timeline.svg"
             ><img src="application/layouts/index/timeline.svg"
                   alt="Timeline of ECMAScript and its implementations"
                   title="Click to enlarge" style="width: 100%"></a>
          <figcaption>Timeline of ECMAScript and its implementations (click to enlarge)</figcaption>
        </figure>
<!--
        <table class="timeline">
          <caption>
            Timeline of ECMAScript editions and implementations
          </caption>
          <thead>
            <tr>
              <th rowspan="2">Date</th>
              <th colspan="2">1996</th>
              <th>1997</th>
              <th>1998</th>
              <th>1999</th>
              <th>2000</th>
              <th>2001</th>
              <th>2002</th>
              <th>2003</th>
              <th>2004</th>
              <th>2005</th>
              <th>2006</th>
              <th colspan="4">2007</th>
              <th colspan="2">2008</th>
              <th>2009</th>
              <th colspan="2">2010</th>
              <th>2011</th>
            </tr>
            <tr>
              <th>1996-03</th>
              <th>1996-08</th>
              <th>1997-06</th>
              <th>1998-08</th>
              <th>1999-05</th>
              <th>2000-11</th>
              <th></th>
              <th>2002-08</th>
              <th></th>
              <th>2004-11</th>
              <th></th>
              <th>2006-07</th>
              <th>2007-02</th>
              <th>2007-04</th>
              <th>2007-06</th>
              <th>2007-08</th>
              <th>2008-02</th>
              <th>2008-07</th>
              <th></th>
              <th>2010-01</th>
              <th>2010-03</th>
              <th>2011-03</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th rowspan="8">JavaScript</th>
              <td class="blue">1.0</td>
              <td class="blue">1.1</td>
              <td class="blue">1.2</td>
              <td colspan="5" class="blue">1.3</td>
            </tr>
            <tr>
              <td colspan="4"></td>
              <td colspan="2" class="blue">1.4</td>
            </tr>
            <tr>
              <td colspan="5"></td>
              <td colspan="9" class="blue">1.5</td>
            </tr>
            <tr>
              <td colspan="9"></td>
              <td colspan="7" class="blue">1.6</td>
            </tr>
            <tr>
              <td colspan="11"></td>
              <td colspan="10" class="blue">1.7</td>
            </tr>
            <tr>
              <td colspan="13"></td>
              <td colspan="8" class="blue">1.8</td>
            </tr>
            <tr>
              <td colspan="17"></td>
              <td colspan="5" class="blue">1.8.1</td>
            </tr>
            <tr>
              <td colspan="19"></td>
              <td colspan="3" class="blue">1.8.2</td>
            </tr>
            <tr>
              <th>Rhino</th>
              <td colspan="4"></td>
              <td colspan="2" class="blue">1.4R3</td>
            </tr>
            <tr>
              <th rowspan="2">Netscape</th>
              <td class="blue">Navigator 2.0</td>
              <td class="blue">3.0</td>
              <td class="nowrap blue">4.0 – 4.05</td>
              <td colspan="5" class="blue">4.06 – 4.8</td>
            </tr>
            <tr>
              <td colspan="5"></td>
              <td colspan="9" class="blue">Navigator 6.x –&nbsp;Browser 8.1.3</td>
              <td colspan="3" class="blue">Navigator 9.0b1 –&nbsp;9.0.0.6</td>
            </tr>
            <tr>
              <th>JScript</th>
              <td></td>
              <td class="blue">1.0</td>
              <td colspan="2" class="blue">3.0</td>
              <td class="blue">3.1</td>
              <td class="nowrap blue">4.0 – 4.1</td>
              <td colspan="3" class="blue">5.0</td>
              <td colspan="2" class="blue">5.1</td>
              <td colspan="3" class="blue">5.5</td>
              <td colspan="11" class="blue">5.6</td>
              <td colspan="7" class="blue">5.7</td>
              <td colspan="24" class="blue">5.8</td>
            </tr>
            <tr>
              <th>Internet Explorer</th>
              <td></td>
              <td class="blue">3.0</td>
              <td colspan="2" class="blue">4.0</td>
              <td class="blue">4.01</td>
            </tr>
            <tr>
              <th>ECMAScript</th>
              <td colspan="2"></td>
              <td colspan="2" class="blue">1</td>
              <td colspan="5" class="blue">2</td>
              <td colspan="4" class="blue">3</td>
              <td colspan="25" class="blue">4</td>
              <td></td>
              <td colspan="18" class="blue">5</td>
            </tr>
            <tr>
              <th>Opera</th>
              <td colspan="7"></td>
              <td class="blue">3.60</td>
            </tr>
          </tbody>
        </table>
 -->
      </section>

      <section>
        <div>
          <h3><a name="javascript" id="javascript">Netscape/Mozilla.org&nbsp;JavaScript
            Version Information</a><a href="#fn-javascript"><sup>1)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            JavaScript versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th class="right">JavaScript</th>
              <th><a
                href="http://e-pla.net/documents/manuals/javascript-1.0/"
                title="JavaScript Authoring Guide for JavaScript 1.0"
                >1.0</a></th>
              <th><a
                href="http://web.archive.org/wp.netscape.com/eng/mozilla/3.0/handbook/javascript/"
                title="JavaScript Guide for JavaScript 1.1 (archived at the Internet Wayback Machine)"
                >1.1</a></th>
              <th><a
                href="http://research.nihonsoft.org/javascript/jsref/"
                title="Client-side JavaScript 1.2 Reference (archived at Nihonsoft Research)"
                >1.2</a></th>
              <th><a
                href="http://research.nihonsoft.org/javascript/ClientReferenceJS13/"
                title="Client-side JavaScript 1.3 Reference (archived at Nihonsoft Research)"
                >1.3</a></th>
              <th><a
                href="http://research.nihonsoft.org/javascript/CoreReferenceJS14/"
                title="Core JavaScript 1.4 Reference (archived at Nihonsoft Research)"
                >1.4</a></th>
              <th><a href="http://replay.waybackmachine.org/20061205033609/http://www.mozilla.org/js/language/js20/"
                   >2.0</a> (historic)</th>
              <th><a
                href="http://developer.mozilla.org/en/docs/Core_JavaScript_1.5_Reference"
                title="Core JavaScript 1.5 Reference"
                >1.5</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.6"
                title="New in JavaScript 1.6"
                >1.6</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.7"
                title="New in JavaScript 1.7"
                >1.7</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.8"
                title="New in JavaScript 1.8"
                >1.8</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.8.1"
                title="New in JavaScript 1.8.1"
                >1.8.1</a></th>
              <th><a
                href="https://developer.mozilla.org/En/Firefox_3.6_for_developers#JavaScript"
                title="New in JavaScript 1.8.2"
                >1.8.2</a></th>
              <th><a
                href="https://developer.mozilla.org/en/JavaScript/New_in_JavaScript/1.8.5"
                title="New in JavaScript 1.8.5"
                >1.8.5</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_5_for_developers#JavaScript"
                title="Firefox 5 for developers: JavaScript"
                >1.8.6</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_6_for_developers#JavaScript"
                title="Firefox 6 for developers: JavaScript"
                >Firefox 6</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_7_for_developers#JavaScript"
                title="Firefox 7 for developers: JavaScript"
                >7</a></th>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_8_for_developers#JavaScript"
                title="Firefox 6 for developers: JavaScript"
                >8</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_10_for_developers#JavaScript"
                title="Firefox 10 for developers: JavaScript"
                >10</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_12_for_developers#JavaScript"
                title="Firefox 12 for developers: JavaScript"
                >12</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_13_for_developers#JavaScript"
                title="Firefox 13 for developers: JavaScript"
                >13</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_15_for_developers#JavaScript"
                title="Firefox 15 for developers: JavaScript"
                >15</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_16_for_developers#JavaScript"
                title="Firefox 16 for developers: JavaScript"
                >16</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_17_for_developers#JavaScript"
                title="Firefox 17 for developers: JavaScript"
                >17</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_18_for_developers#JavaScript"
                title="Firefox 18 for developers: JavaScript"
                >18</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_19_for_developers#JavaScript"
                title="Firefox 19 for developers: JavaScript"
                >19</a></td>
              <td><a
                href="https://developer.mozilla.org/en/Firefox_20_for_developers#JavaScript"
                title="Firefox 20 for developers: JavaScript"
                >20</a></td>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="24"><a name="fn-javascript" id="fn-javascript"
                >1)</a><a href="#javascript" class="backref">&#8593;</a>
                Version information from the JavaScript Guides and References;
                release dates from <a href="about:">about:</a>&nbsp;documents,
                <a href="http://www.mozilla.org/releases/cvstags.html">mozilla.org</a>
                and <a href="http://en.wikipedia.org/wiki/Mozilla_Firefox#History"
                       >Wikipedia</a>.</td>
            </tr>
          </tfoot>
          <tbody>
            <tr class="header">
              <th colspan="27">Implementations</th>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/js/spidermonkey/"
                     >Netscape/Mozilla.org SpiderMonkey</a> (in C)</th>
              <td>1.0</td>
              <td>1.1</td>
              <td>1.2</td>
              <td>1.3</td>
              <td>1.4</td>
              <td>&nbsp;</td>
              <td>1.5</td>
              <td>1.6</td>
              <td>1.7</td>
              <td>1.8</td>
              <td>1.8.1 (<a
                href="https://developer.mozilla.org/En/SpiderMonkey/Internals/Tracing_JIT"
                >TraceMonkey</a>)</td>
              <td>1.8.2</td>
              <td>1.8.5 (<a
                href="https://wiki.mozilla.org/JaegerMonkey">JägerMonkey</a>)</td>
              <td>1.8.6</td>
              <td>?</td>
              <td>?</td>
              <td>?</td>
              <td>?</td>
              <td>?</td>
              <td>?</td>
              <td>?</td>
              <td>?</td>
              <td>?</td>
              <td>? (<a
                href="https://wiki.mozilla.org/IonMonkey">IonMonkey</a>)</td>
              <td>?</td>
              <td>?</td>
            </tr>
            <tr>
              <th><a href="http://wayback.archive.org/web/20090201134254/http://www.mozilla.org/js/language/Epimetheus.html"
                     >Mozilla.org Epimetheus</a> (in C++)</th>
              <td colspan="5"></td>
              <td>+</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/rhino/"
                     >Netscape/Mozilla.org Rhino</a> (in Java)</th>
              <td colspan="4"></td>
              <td>1.4R3 (<span title="1999-05-10">1999</span>)</td>
              <td>&nbsp;</td>
              <td><a href="http://www.mozilla.org/rhino/rhino15R1.html"
                     >1.5R1</a>–<a
                     href="http://www.mozilla.org/rhino/rhino15R5.html"
                     >1.5R5</a>
                (<span title="2000-09-10 –&nbsp;2004-03-25">2000–2004</span>)</td>
              <td><a href="http://www.mozilla.org/rhino/rhino16R1.html"
                     >1.6R1</a>–<a
                     href="https://developer.mozilla.org/en/New_in_Rhino_1.6R7"
                     >1.6R7</a>
                (<span title="2004-11-29 –&nbsp;2007-08-20">2004–2007</span>)</td>
              <td><a href="https://developer.mozilla.org/en/New_in_Rhino_1.7R1"
                     >1.7R1</a>–<a
                     href="https://developer.mozilla.org/en/New_in_Rhino_1.7R2"
                     >1.7R2</a>
                (<span title="2008-03-06 –&nbsp;2009-03-22">2008–2009</span>)</td>
              <td><a href="https://developer.mozilla.org/en/New_in_Rhino_1.7R3"
                     >1.7R3</a>
                (2011&#8209;06&#8209;03)</td>
            </tr>

            <tr class="header">
              <th colspan="27">Layout Engines</th>
            </tr>
            <tr>
              <th><a href="https://developer.mozilla.org/en/docs/Gecko">Netscape/Mozilla.org
              <abbr title="Next Generation Layout Engine">NGLayout</abbr>/Gecko</a></th>
              <td colspan="6"></td>
              <td>0.6–1.8a6</td>
              <td>1.8b1–1.8</td>
              <td>1.8.1</td>
              <td>1.9</td>
              <td>1.9.1</td>
              <td>1.9.2</td>
              <td>1.9.3, 2.0</td>
              <td>5.0</td>
              <td>6.0</td>
              <td>7.0</td>
              <td>8.0–9.0</td>
              <td>10.0–11.0</td>
              <td>12.0</td>
              <td>13.0–14.0</td>
              <td>15.0</td>
              <td>16.0</td>
              <td>17.0</td>
              <td>18.0</td>
              <td>19.0</td>
              <td>20.0</td>
            </tr>

            <tr class="header">
              <th colspan="27">Web Browsers</th>
            </tr>
            <tr>
              <th><a href="http://browser.netscape.com/">Netscape
                Navigator/Browser</a>&nbsp;<span
                title="Development discontinued">&#8224;</span></th>
              <td>Navigator 2.0&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1996-03">1996</span>)</td>
              <td>3.0&nbsp;<span title="End-of-life">&#8224;</span> (<span title="1996-08">1996</span>)</td>
              <td>4.0–4.05&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1997-06">1997</span>)</td>
              <td>4.06–4.8&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1998-08-17 –&nbsp;2002-08">1998–2002</span>)</td>
              <td colspan="2">&nbsp;</td>
              <td>Navigator&nbsp;6.x –&nbsp;Browser&nbsp;8.1.3&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2000-11-14 –&nbsp;2007-04-02">2000–2007</span>)</td>
              <td>-</td>
              <td>Navigator&nbsp;9.0b1 –&nbsp;9.0.0.6&nbsp;<span
                title="End-of-life">&#8224;</span><br>
              (<span title="2007-06-05 –&nbsp;2008-02-29">2007–2008</span>)</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.com/firefox/">Mozilla
                Phoenix/Firebird/Firefox</a></th>
              <td colspan="6"></td>
              <td>Phoenix&nbsp;0.1 –&nbsp;Firefox&nbsp;1.0.8&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2002-09-23 –&nbsp;2006-04-13">2002–2006</span>)</td>
              <td>Firefox&nbsp;1.5a1–1.5.0.12&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2005-05-31 –&nbsp;2006-05-26">2005–2007</span>)</td>
              <td>2.0b1–2.0.0.18&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2006-07-12 –&nbsp;2008-11-12">2006–2008</span>)</td>
              <td>3.0a2–3.0.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2007-02-07 –&nbsp;2010-03-30">2007–2010</span>)</td>
              <td>3.1a1–3.5.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2008&#8209;07&#8209;28 –&nbsp;2011&#8209;04&#8209;28"
                       >2008–2011</span>)</td>
              <td>3.6a1–3.6.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2010&#8209;01&#8209;21 –&nbsp;2011&#8209;07&#8209;11">2010–2011</span>)</td>
              <td>3.7a1–4.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2010&#8209;02&#8209;10 –&nbsp;2011&#8209;04&#8209;28"
                       >2010–2011</span>)</td>
              <td>5.0–5.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;06&#8209;21 –&nbsp;2011&#8209;07&#8209;11">2011</span>)</td>
              <td>6&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;08&#8209;16">2011</span>)</td>
              <td>7&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;09&#8209;27">2011</span>)</td>
              <td>8–9&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;11&#8209;08 –&nbsp;2012&#8209;01&#8209;30">2011–2012</span>)</td>
              <td>10–11&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;01&#8209;31 –&nbsp;2012&#8209;04&#8209;23">2012</span>)</td>
              <td>12&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;04&#8209;24">2012</span>)</td>
              <td>13–14&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;06&#8209;05 –&nbsp;2012&#8209;08&#8209;14">2012</span>)</td>
              <td>15&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;08&#8209;14">2012</span>)</td>
              <td>16&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;10&#8209;09">2012</span>)</td>
              <td>17<br>
                (<span title="2012&#8209;11&#8209;20">2012</span>)</td>
              <td>18&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2013&#8209;01&#8209;08">2013</span>)</td>
              <td>19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2013&#8209;02&#8209;19">2013</span>)</td>
              <td>20<br>
                (<span title="2013&#8209;04&#8209;02">2013&#8209;04&#8209;02</span>)</td>
            </tr>

            <tr class="header">
              <th colspan="27">Other Clients</th>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/products/mozilla1.x/">Mozilla
                Application&nbsp;Suite</a>&nbsp;<span
                title="Development discontinued">&#8224;</span></th>
              <td colspan="6"></td>
              <td>0.6–1.8a6–1.7.13&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2000-12-06 –&nbsp;2006-04-21">2000–2006</span>)</td>
              <td>1.8b1&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005-02-23">2005</span>)</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/projects/seamonkey/">Mozilla
              SeaMonkey</a></th>
              <td colspan="7"></td>
              <td>1.0a–1.0.9&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005-09-15 –&nbsp;2007-05-30">2005–2007</span>)</td>
              <td>1.1a–1.1.19&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2006-08-30 –&nbsp;2010-03-16">2006–2010</span>)</td>
              <td>&nbsp;</td>
              <td>2.0a1–2.0.12<br>
                (2008&#8209;10&#8209;05 –&nbsp;2011&#8209;03&#8209;02)</td>
              <td>&nbsp;</td>
              <td>2.1a1–2.1<br>
                (2010&#8209;05&#8209;18 –&nbsp;2011&#8209;06&#8209;10)</td>
              <td>2.2b1–2.2<br>
                (2011&#8209;06&#8209;22 –&nbsp;2011&#8209;07&#8209;07)</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.com/thunderbird/">Mozilla
              Thunderbird</a></th>
              <td colspan="6"></td>
              <td>0.1–1.0.8&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2003-07-28 –&nbsp;2006-04-21">2003–2006</span>)</td>
              <td>1.1a1–1.5.0.14&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005-06-02 –&nbsp;2007-12-19">2005–2007</span>)</td>
              <td>2.0a1–2.0.0.24&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2006-07-28 –&nbsp;2010-03-15">2006–2010</span>)</td>
              <td>3.0a1, 3.0a2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008-05-13, 2008-08-12">2008</span>)</td>
              <td>3.0a3–3.0.11&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008-10-14 –&nbsp;2010-12-09">2008–2010</span>)</td>
              <td>3.1a1–3.1.12<br>
                (2010&#8209;02&#8209;03 –&nbsp;2011&#8209;08&#8209;16)</td>
              <td>3.3a1–3.3a3<br>
                (2010&#8209;11&#8209;23 –&nbsp; 2011&#8209;01&#8209;20)</td>
              <td>5.0b1–5.0<br>
                (2011&#8209;06&#8209;02 –&nbsp;2011&#8209;06&#8209;28)</td>
            </tr>

            <tr class="header">
              <th colspan="27">Web Servers</th>
            </tr>
            <tr>
              <th><a href="http://wp.netscape.com/enterprise/">Netscape
              Enterprise&nbsp;Server</a>/<br>
              <a href="http://en.wikipedia.org/wiki/iPlanet"
                title="Wikipedia: iPlanet"
              >iPlanet</a>&nbsp;Web&nbsp;Server/<br>
              <a href="http://en.wikipedia.org/wiki/Sun_ONE"
                title="Wikipedia: Sun ONE"
              >Sun&nbsp;ONE</a> Web&nbsp;Server/<br>
              <a href="http://www.sun.com/software/products/appsrvr/">Sun
              Java&nbsp;System Web&nbsp;Server</a></th>
              <td></td>
              <td>2.0</td>
              <td>3.0</td>
              <td></td>
              <td>4.0/<a href="http://docs.sun.com/source/816-5930-10/"
                title="iPlanet Web Server, Enterprise Edition Server-Side JavaScript 1.4 Guide"
              >4.1</a> (1999)</td>
              <td>&nbsp;</td>
              <td>6.0</td>
            </tr>
            <tr>
              <th><a href="http://firecat.nihonsoft.org/">NihonSoft
              firecat</a></th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>1.0.x Beta4 (2008)</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <div>
          <h3><a name="jscript" id="jscript">Microsoft&nbsp;JScript Version
            Information</a><a href="#fn-jscript"><sup>2)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            JScript versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th class="right">JScript</th>
              <th>1.0</th>
              <th>2.0</th>
              <th>3.0</th>
              <th>3.1.3510</th>
              <th>4.0</th>
              <th>5.0</th>
              <th>5.1.5010</th>
              <th>5.5.6330</th>
              <th><a
                href="http://msdn2.microsoft.com/en-us/library/hbxc2t98.aspx"
                title="JScript 5.6 documentation"
              >5.6.6626</a> –&nbsp;5.6.8819</th>
              <th>5.7.5730</th>
              <th>5.7.17184</th>
              <th>5.8.18241</th>
              <th>7.0 (.NET)</th>
              <th><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a%28VS.71%29.aspx"
                title="JScript 7.1 (.NET) documentation"
              >7.1 (.NET)</a></th>
              <th><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a%28VS.80%29.aspx"
                title="JScript 8.0 documentation"
              >8.0</a></th>
              <th>9.0.16421
               (<a href="http://en.wikipedia.org/wiki/Chakra_(JavaScript_engine)"
                   >Chakra</a>)</th>
              <th><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a.aspx"
                title="JScript 10.0 documentation"
              >10.0</a></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="16"><a name="fn-jscript" id="fn-jscript"
                >2)</a><a href="#jscript" class="backref">&#8593;</a>
                Version information from <a
                  href="http://msdn.microsoft.com/library/en-us/jscript7/html/jsoriVersionInformation.asp"
                ><acronym title="Microsoft Developer Network">MSDN</acronym>&nbsp;Library</a>;
                release&nbsp;dates from MSDN&nbsp;Library, <a
                  href="http://www.blooberry.com/indexdot/history/ie.htm"
                  title="Browser History: Windows Internet Explorer"
                >blooberry.com</a> and <a href="http://en.wikipedia.org/">Wikipedia</a>,
                end-of-life&nbsp;(&#8224;) dates from <a
                 href="http://support.microsoft.com/gp/lifeselectindex"
                  >support.microsoft.com</a>.<br>
                <em>Note that the language version supported by an environment
                may be greater than specified here due to security updates.
                When in doubt, use the <a href="#script-engine-test"
                >script engine test above</a> to determine the true version.</em>
              </td>
            </tr>
          </tfoot>
          <tbody>
            <tr class="header">
              <th colspan="18">Implementations</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/net/">Microsoft .NET Framework</a></th>
              <td colspan="12"></td>
              <td>1.0 (2002-01)</td>
              <td>1.1 (2003)</td>
              <td>2.0–3.5&nbsp;SP1 (2005–2008)</td>
              <td></td>
              <td>4.0&#8212; (2010-04-12&#8212;)</td>
            </tr>

            <tr class="header">
              <th colspan="18">Web Browsers</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/ie/">Microsoft Internet Explorer</a></th>
              <td>3.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1996-08</span> <a
                href="http://en.wikipedia.org/wiki/Common_Era"
              ><acronym title="Common Era">CE</acronym></a>)</td>
              <td></td>
              <td class="nowrap">4.0 <span title="End-of-life">&#8224;</span><br>
                (1997-09)</td>
              <td class="nowrap">4.01 <span title="End-of-life">&#8224;</span><br>
              	(1997-11)</td>
              <td></td>
              <td>5.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1999-03</span>
                <span class="nowrap">– 2005-06)</span></td>
              <td class="nowrap">5.01 <span title="End-of-life">&#8224;</span></td>
              <td>5.5&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000-07</span>
                <span class="nowrap">–&nbsp;2005-12)</span></td>
              <td>6.0 for <abbr title="Windows 95 and 98">Win9x</abbr>/NT/XP&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2001-10)</span></td>
              <td>7.0 for <abbr title="Windows">Win</abbr>XP+<br>
                <span class="nowrap">(2006-10)</span></td>
              <td>8.0 beta 1 for <abbr title="Windows">Win</abbr>XP SP2+<br>
                <span class="nowrap">(2008-03)</span></td>
              <td>8.0 beta&nbsp;2 for <abbr title="Windows">Win</abbr>XP SP2+<br>
                <span class="nowrap">(2008-08)</span></td>
              <td colspan="3"></td>
              <td><span title="9.0.8112.16421">9.0</span> for Vista SP2+ / Server&nbsp;2008<br>
                (2011&#8209;03&#8209;14)</td>
            </tr>

            <tr class="header">
              <th colspan="18">Web Servers</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/iis/">Microsoft Internet
              Information Server/Services</a></th>
              <td colspan="2"></td>
              <td>4.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1998–2002)</span></td>
              <td colspan="5"></td>
              <td>5.1–6.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000–2005)</span></td>
              <td colspan="2">7.0<br>
                <span class="nowrap">(2008)</span></td>
              <td>7.5<br>
                <span class="nowrap">(2009)</span></td>
            </tr>

            <tr class="header">
              <th colspan="18">Operating Systems</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/windows/">Microsoft Windows</a></th>
              <td></td>
              <td>NT&nbsp;4.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1996)</span></td>
              <td colspan="4"></td>
              <td>2000&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000-02</span>
                <span class="nowrap">–&nbsp;2005-06)</span></td>
              <td><acronym title="Millennium Edition">Me</acronym>&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000-09</span>
                <span class="nowrap">–&nbsp;2005-12)</span></td>
              <td><abbr title="eXPeriment^H^H^H^Hence ;-)">XP</abbr><br>
                <span class="nowrap">(2001-10)</span></td>
              <td colspan="2">Vista<br>
                <span class="nowrap">(2008-03)</span></td>
              <td>7<br>
                <span class="nowrap">(2009-10)</span></td>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/windowsserver2003/"
                     >Microsoft Windows Server</a></th>
              <td colspan="8"></td>
              <td>2003<br>
                <span class="nowrap">(2003-04)</span></td>
              <td colspan="2">2008<br>
                <span class="nowrap">(2008-02)</span></td>
              <td>2008&nbsp;R2<br>
                <span class="nowrap">(2009-09)</span></td>
              <td colspan="2">&nbsp;</td>
              <td>2008</td>
              <td>&nbsp;</td>
              <td>2008&nbsp;R2</td>
            </tr>

            <tr class="header">
              <th colspan="18"><acronym
                title="Integrated Development Environment"
              >IDE</acronym>s</th>
            </tr>
            <tr>
              <th><a href="http://www.microsoft.com/visualstudio/en-us/products"
                     >Microsoft Visual Studio</a></th>
              <td colspan="4"></td>
              <td>6.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1998–2005)</span></td>
              <td colspan="7"></td>
              <td>.NET&nbsp;7.0<br>(2002)</td>
              <td>.NET&nbsp;7.1<br>(2003)</td>
              <td>8.0–9.0<br>(2005–2008)</td>
              <td></td>
              <td>10.0&#8212;<br>(2010-04-12&#8212;)</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <div>
          <h3><a name="v8" id="v8">Google&nbsp;V8 Version
          Information</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            V8 versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>V8&nbsp;0.3</th>
              <th>0.4</th>
              <th>1.2</th>
              <th>1.3</th>
              <th>2.0</th>
              <th>2.1</th>
              <th>2.2</th>
              <th>2.3.11.22</th>
              <th>2.4.9.19</th>
              <th>2.5.9.6</th>
              <th>3.0.12.18</th>
              <th>3.1.4.0</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="http://www.google.com/chrome/">Google Chrome</a></th>
              <td>0.2–1.0<br>
                (2008-09&nbsp;<a
                href="http://en.wikipedia.org/wiki/Common_Era"
              ><acronym title="Common Era">CE</acronym></a>&#8212;2008-12)</td>
              <td>2.0<br>
                (2009-05)</td>
              <td>3.0<br>
                (2009-10)</td>
              <td>4.0.249<br>
                (2010-01-25)</td>
              <td>5.0.307<br>
                (2010-01-30)</td>
              <td>5.0.342<br>
                (2010-04-07)</td>
              <td>6.0.466.0<br>
                (2010-07-15)</td>
              <td>7.0.517<br>
                (2010-10-21)</td>
              <td>8.0.552<br>
                (2010-12-02)</td>
              <td>9.0.597<br>
                (2011-02-03)</td>
              <td>10.0.648<br>
                (2011-03-11)</td>
              <td>11.0.672<br>
                (2011-03-08)</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <div>
          <h3><a name="jsc" id="jsc">Apple&nbsp;JavaScriptCore Version
            Information</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            Apple JavaScriptCore versions and the user agents that
            support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>JavaScriptCore&nbsp;48–312.6</th>
              <th>412–419.13</th>
              <th>522.11–523.10</th>
              <th>525.13</th>
              <th>525.19</th>
              <th>525.27.1</th>
              <th>530.17</th>
              <th>531.9</th>
              <th>531.21.8</th>
              <th>531.22.7</th>
              <th>533.16</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="http://apple.com/safari/">Apple Safari</a></th>
              <td>0.8–1.3.2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (2003–2006&nbsp;<a
                href="http://en.wikipedia.org/wiki/Common_Era"
                ><acronym title="Common Era">CE</acronym></a>)</td>
              <td>2.0–2.0.4<br>
                (2005-04 –&nbsp;2006-01)</td>
              <td>3.0–3.0.4<br>
                 (2007-06 –&nbsp;2007-10)</td>
              <td>3.1<br>
                (2008-03)</td>
              <td>3.1.2<br>
                (2008-06)</td>
              <td>3.2.1<br>
                (2008-11)</td>
              <td>4.0<br>
                (2009-06)</td>
              <td>4.0.3<br>
                (2009-08)</td>
              <td>4.0.4<br>
                (2009-11)</td>
              <td>4.0.5<br>
                (2010-03-11)</td>
              <td>5.0<br>
                (2010-06-07)</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <div>
          <h3><a name="opera" id="opera">Opera&nbsp;ECMAScript Version
            Information</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            Opera ECMAScript versions and the user agents that support
            them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>Opera&nbsp;ECMAScript&nbsp;3.60</th>
              <th>5.02</th>
              <th>6.06</th>
              <th>7.02</th>
              <th>8.0</th>
              <th>9.27</th>
              <th>9.52</th>
              <th>9.62</th>
              <th>9.64</th>
              <th>10.10</th>
              <th>10.50</th>
              <th>10.51</th>
              <th>10.54</th>
              <th>10.63</th>
              <th>11.50</th>
            </tr>
          </thead>
          <tbody>
            <tr class="header">
              <th colspan="16">Implementations</th>
            </tr>
            <tr>
              <td></td>
              <td colspan="3">Linear A</td>
              <td colspan="3">Linear B</td>
              <td colspan="4">Futhark</td>
              <td colspan="5">Carakan</td>
            </tr>
            <tr class="header">
              <th colspan="16">Layout Engines</th>
            </tr>
            <tr>
              <td></td>
              <td colspan="3">Elektra</td>
              <td colspan="2">Presto 1.0</td>
              <td>2.0</td>
              <td>2.1</td>
              <td colspan="2">2.1.1</td>
              <td>2.4</td>
              <td colspan="3">2.5</td>
              <td>2.6</td>
              <td>2.7</td>
            </tr>
            <tr class="header">
              <th colspan="16">Web Browsers</th>
            </tr>
            <tr>
              <th><a href="http://opera.com/">Opera Browser</a></th>
              <td>3.60&nbsp;<span title="End-of-life">&#8224;</span><br>
                (1999-05)</td>
              <td>5.02&nbsp;<span title="End-of-life">&#8224;</span><br>
              	(2000-12)</td>
              <td>6.06<br>
                (2001-11)</td>
              <td>7.02<br>
                (2003–2005)</td>
              <td>8.0<br>
                (2005–2008)</td>
              <td>9.27<br>
                (2008)</td>
              <td>9.52<br>
                (2008)</td>
              <td>9.62<br>
                (2008–2009)</td>
              <td>9.64<br>
                (2009)</td>
              <td>10.10<br>
                (2009–2010)</td>
              <td>10.50<br>
                (2010-03-02)</td>
              <td>10.51<br>
                (2010-03-22)</td>
              <td>10.54<br>
                (2010-06-21)</td>
              <td>10.63<br>
                (2010-10-12)</td>
              <td>11.50<br>
                (2011-06-28)</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <div>
          <h3><a name="actionscript" id="actionscript"
            >Macromedia/Adobe&nbsp;ActionScript Versions</a><a
            href="#fn-actionscript"><sup>3)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            ActionScript versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>ActionScript&nbsp;1.0</th>
              <th>2.0</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="9"><a name="fn-actionscript" id="fn-actionscript"
                >3)</a><a href="#actionscript" class="backref">&#8593;</a>
                Version information from <a
                  href="http://macromedia.com/software/flash/"
                >Macromedia</a></td>
            </tr>
          </tfoot>
          <tbody>
            <tr>
              <th><a href="http://macromedia.com/software/flash/">Macromedia
              Flash</a></th>
              <td>5.0–MX (2000–2003)</td>
              <td>7.1.1 (MX 2004)&#8212; (2004&#8212;)</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <div>
          <h3><a name="ecmascript" id="ecmascript">ECMAScript Compatibility</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>

          <p>The following table provides a rough overview of ECMAScript Editions
          and relations between them and versions of their implementations. Note
          that conforming implementations are allowed to <em>extend</em>
          ECMAScript, so these are <em>by no means</em> 1:n relations; instead,
          this is the result of a comparison of most common language features.</p>

          <p style="text-align: left">See <a href="#features">Language&nbsp;Features</a>
          above for details.</p>
        </div>

        <table class="versions">
          <caption>
            ECMAScript editions and versions of implementations that
            implement them best
          </caption>
          <thead>
            <tr>
              <td></td>
              <th>ECMAScript&nbsp;Edition&nbsp;1</th>
              <th>2</th>
              <th>3</th>
              <th>4<br>
              (Working&nbsp;Draft; abandoned)</th>
              <th>5</th>
              <th>6<br>
              ("Harmony", Working&nbsp;Draft)</th>
            </tr>
            <tr>
              <th></th>
              <td><a href="http://www.mozilla.org/js/language/">June&nbsp;1997</a></td>
              <td><a href="http://www.mozilla.org/js/language/">August&nbsp;1998</a></td>
              <td><a
                href="http://www.ecma-international.org/publications/standards/Ecma-262.htm"
              >December&nbsp;1999</a> –&nbsp;<a
                href="http://developer.mozilla.org/en/docs/JavaScript_Language_Resources#JavaScript_1.x"
              >March&nbsp;2000</a></td>
              <td><a href="http://www.ecmascript.org/">August&nbsp;2000
              –&nbsp;June&nbsp;2003 –&nbsp;2008</a></td>
              <td><a href="http://www.ecmascript.org/">April&nbsp;2009 –&nbsp;December&nbsp;2009</a></td>
              <td><a href="http://www.ecmascript.org/">April&nbsp;2009&#8212;</a></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="#actionscript">ActionScript</a></th>
              <td colspan="2"></td>
              <td>2.0 (2004)</td>
              <td>3.0 (2008&#8212;)</td>
            </tr>
            <tr>
              <th><a href="#javascript">JavaScript</a></th>
              <td>1.1, 1.3, 1.4</td>
              <td></td>
              <td>1.5–1.8.1.x</td>
              <td>2.0</td>
              <td>1.8.1&#8212; (2008-05&#8212;)</td>
            </tr>
            <tr>
              <th><a href="#jsc">JavaScriptCore</a></th>
            </tr>
            <tr>
              <th><a href="#jscript">JScript</a></th>
              <td>1.0 (1996)</td>
              <td></td>
              <td>5.5&#8212; (2000&#8212;)</td>
              <td>7.0&#8212; (2000&#8212;)</td>
            </tr>
            <tr>
              <th>KJS</th>
              <td colspan="2"></td>
              <td>1.0</td>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="http://www.opera.com/docs/specs/js/ecma/">Opera</a></th>
              <td colspan="2"></td>
              <td>6.0 (2001-12)</td>
            </tr>
            <tr>
              <th><a href="#v8">V8</a></th>
              <td colspan="2"></td>
              <td>0.3</td>
            </tr>
          </tbody>
        </table>

        <table class="versions" style="margin-top: 1em">
          <caption>
            Editions of ECMAScript for XML and implementations that
            implement them best
          </caption>
          <thead>
            <tr>
              <td></td>
              <th>ECMAScript&nbsp;for&nbsp;XML (E4X)</th>
            </tr>
            <tr>
              <td></td>
              <td><a
                href="http://www.ecma-international.org/publications/standards/Ecma-357.htm"
              >June&nbsp;2004</a></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="#actionscript">ActionScript</a></th>
              <td>2.0</td>
            </tr>
            <tr>
              <th><a href="#javascript">JavaScript</a></th>
              <td>1.6+</td>
            </tr>
            <tr>
              <th><a href="#jsc">JavaScriptCore</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="#jscript">JScript</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th>KJS</th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="http://www.opera.com/docs/specs/js/ecma/">Opera</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="#v8">V8</a></th>
              <td>-</td>
            </tr>
          </tbody>
        </table>
      </section>
    </section>

    <section>
      <div>
        <h2><a name="contributors" id="contributors">List of Contributors</a></h2>

        <div><a href="#toc">&#8593; Table of contents</a></div>

        <p><em>Thanks to (in alphabetical order):</em></p>
      </div>

      <ul>
        <li><a href="http://asenbozhilov.com/">Asen Bozhilov
          (<span lang="bg">Асен Божилов</span>)</a>
          &lt;<a href="<?php echo randomEsc('mailto:asen.bozhilov@gmail.com'); ?>"
          ><?php echo randomEsc('asen.bozhilov@gmail.com'); ?></a>&gt;
          for corrections on ECMAScript Editions and feature suggestions</li>
        <li>BootNic &lt;<a href="<?php echo randomEsc('mailto:bootnic.bounce@gmail.com'); ?>"
          ><?php echo randomEsc('bootnic.bounce@gmail.com'); ?></a>&gt;
          for helping with the scrollable tbody workaround for IE: Message-ID&nbsp;<a
          href="http://groups.google.com/groups/search?as_umsgid=20100305112229.454328ac@bootnic.eternal-september.org"
          >&lt;20100305112229.454328ac@bootnic.eternal-september.org&gt;</a></li>
        <li><a href="http://perfectionkills.com/">Juriy&nbsp;'kangax'&nbsp;Zaytsev
          (<span lang="ru">Юрий Зайцев</span>)</a>
          &lt;<a href="<?php echo randomEsc('mailto:kangax@gmail.com'); ?>"
          ><?php echo randomEsc('kangax@gmail.com'); ?></a>&gt;
          for tests with Safari&nbsp;2.0.2: Message-ID&nbsp;<a
          href="http://groups.google.com/groups/search?as_umsgid=MpOdnVEQCfgNMN_WnZ2dnUVZ_rNi4p2d@giganews.com"
          >&lt;MpOdnVEQCfgNMN_WnZ2dnUVZ_rNi4p2d@giganews.com&gt;</a></li>
        <li>Michael&nbsp;Winter
          &lt;<a href="<?php echo randomEsc('mailto:m.winter@blueyonder.co.uk'); ?>"
          ><?php echo randomEsc('m.winter@blueyonder.co.uk'); ?></a>&gt;
          for tests with IE&nbsp;4.01 and NN&nbsp;4.08: Message-ID&nbsp;<a
          href="http://groups.google.com/groups/search?as_umsgid=urctf.17012$iz3.5930@text.news.blueyonder.co.uk"
          >&lt;urctf.17012$iz3.5930@text.news.blueyonder.co.uk&gt;</a></li>
      </ul>
    </section>

    <footer>
      <div id="footer">
        <div><a href="http://www.w3.org/html/logo/"
                ><img src="http://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png"
                      width="165" height="64"
                      alt="HTML5 Powered with CSS3 / Styling, and Semantics"
                      title="HTML5 Powered with CSS3 / Styling, and Semantics"></a></div>
        <p>built with<br>
        <a href="http://www.eclipse.org/"
           ><img src="/media/eclipse.jpg" alt="eclipse"
                 style="border: 0; width: 131px; height: 68px"
                 ></a></p>
      </div>
    </footer>