<?php
  if (!$this->edit)
  {
?>
     <a href="<?php echo $this->escape($this->getURL(null, 'edit')); ?>">Edit</a>
<?php
  }
  else
  {
?>
     <a href="<?php echo $this->escape($this->getURL(null, 'endEdit')); ?>">End Edit</a>
<?php
  }
?>
    <form action="<?php echo $this->escape($this->getURL(null, 'saveResult')); ?>" method="POST">
      <table id="features-table"
             summary="Language features and the first editions of ECMAScript or first versions of the implementations that introduced or supported them">
        <thead>
          <?php require_once 'features-head.phtml'; ?>
        </thead>
        <tfoot>
          <?php require_once 'env-list.phtml'; ?>
        </tfoot>
        <tbody id="scroller" class="scroll">
          <?php require_once 'features-list.phtml'; ?>
        </tbody>
      </table>
    </form>
<?php $this->footnotes->flush(); ?>