      <div>
        <h2><a name="version-info" id="version-info">Version Information</a></h2>

        <div><a href="#toc">&#8593; Table of contents</a></div>

        <ul>
          <li><a href="#timeline">Timeline</a></li>
          <li><a href="#javascript">Netscape/Mozilla JavaScript</a></li>
          <li><a href="#jscript">Microsoft JScript</a></li>
          <li><a href="#v8">Google V8 JavaScript</a></li>
          <li><a href="#jsc">Apple JavaScriptCore</a></li>
          <li><a href="#opera">Opera ECMAScript</a></li>
          <li><a href="#actionscript">Adobe ActionScript</a></li>
          <li><a href="#ecmascript">ECMAScript compatibility</a></li>
        </ul>
      </div>

      <section>
        <div>
          <h3><a name="timeline" id="timeline">Timeline</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <figure style="margin-left: 0; margin-right: 0">
          <a href="application/layouts/index/timeline.svg"
             ><img src="application/layouts/index/timeline.svg"
                   alt="Timeline of ECMAScript and its implementations"
                   title="Click to enlarge" style="width: 100%"></a>
          <figcaption>Timeline of ECMAScript and its implementations (click to enlarge)</figcaption>
        </figure>
<?php /*
        <table class="timeline">
          <caption>
            Timeline of ECMAScript editions and implementations
          </caption>
          <thead>
            <tr>
              <th rowspan="2">Date</th>
              <th colspan="2">1996</th>
              <th>1997</th>
              <th>1998</th>
              <th>1999</th>
              <th>2000</th>
              <th>2001</th>
              <th>2002</th>
              <th>2003</th>
              <th>2004</th>
              <th>2005</th>
              <th>2006</th>
              <th colspan="4">2007</th>
              <th colspan="2">2008</th>
              <th>2009</th>
              <th colspan="2">2010</th>
              <th>2011</th>
            </tr>
            <tr>
              <th>1996-03</th>
              <th>1996-08</th>
              <th>1997-06</th>
              <th>1998-08</th>
              <th>1999-05</th>
              <th>2000-11</th>
              <th></th>
              <th>2002-08</th>
              <th></th>
              <th>2004-11</th>
              <th></th>
              <th>2006-07</th>
              <th>2007-02</th>
              <th>2007-04</th>
              <th>2007-06</th>
              <th>2007-08</th>
              <th>2008-02</th>
              <th>2008-07</th>
              <th></th>
              <th>2010-01</th>
              <th>2010-03</th>
              <th>2011-03</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th rowspan="8">JavaScript</th>
              <td class="blue">1.0</td>
              <td class="blue">1.1</td>
              <td class="blue">1.2</td>
              <td colspan="5" class="blue">1.3</td>
            </tr>
            <tr>
              <td colspan="4"></td>
              <td colspan="2" class="blue">1.4</td>
            </tr>
            <tr>
              <td colspan="5"></td>
              <td colspan="9" class="blue">1.5</td>
            </tr>
            <tr>
              <td colspan="9"></td>
              <td colspan="7" class="blue">1.6</td>
            </tr>
            <tr>
              <td colspan="11"></td>
              <td colspan="10" class="blue">1.7</td>
            </tr>
            <tr>
              <td colspan="13"></td>
              <td colspan="8" class="blue">1.8</td>
            </tr>
            <tr>
              <td colspan="17"></td>
              <td colspan="5" class="blue">1.8.1</td>
            </tr>
            <tr>
              <td colspan="19"></td>
              <td colspan="3" class="blue">1.8.2</td>
            </tr>
            <tr>
              <th>Rhino</th>
              <td colspan="4"></td>
              <td colspan="2" class="blue">1.4R3</td>
            </tr>
            <tr>
              <th rowspan="2">Netscape</th>
              <td class="blue">Navigator 2.0</td>
              <td class="blue">3.0</td>
              <td class="nowrap blue">4.0 – 4.05</td>
              <td colspan="5" class="blue">4.06 – 4.8</td>
            </tr>
            <tr>
              <td colspan="5"></td>
              <td colspan="9" class="blue">Navigator 6.x –&nbsp;Browser 8.1.3</td>
              <td colspan="3" class="blue">Navigator 9.0b1 –&nbsp;9.0.0.6</td>
            </tr>
            <tr>
              <th>JScript</th>
              <td></td>
              <td class="blue">1.0</td>
              <td colspan="2" class="blue">3.0</td>
              <td class="blue">3.1</td>
              <td class="nowrap blue">4.0 – 4.1</td>
              <td colspan="3" class="blue">5.0</td>
              <td colspan="2" class="blue">5.1</td>
              <td colspan="3" class="blue">5.5</td>
              <td colspan="11" class="blue">5.6</td>
              <td colspan="7" class="blue">5.7</td>
              <td colspan="24" class="blue">5.8</td>
            </tr>
            <tr>
              <th>Internet Explorer</th>
              <td></td>
              <td class="blue">3.0</td>
              <td colspan="2" class="blue">4.0</td>
              <td class="blue">4.01</td>
            </tr>
            <tr>
              <th>ECMAScript</th>
              <td colspan="2"></td>
              <td colspan="2" class="blue">1</td>
              <td colspan="5" class="blue">2</td>
              <td colspan="4" class="blue">3</td>
              <td colspan="25" class="blue">4</td>
              <td></td>
              <td colspan="18" class="blue">5</td>
            </tr>
            <tr>
              <th>Opera</th>
              <td colspan="7"></td>
              <td class="blue">3.60</td>
            </tr>
          </tbody>
        </table>
 */ ?>
      </section>

      <section>
        <?php include_once 'version-info/javascript.phtml'; ?>
      </section>

      <section>
        <?php include_once 'version-info/jscript.phtml'; ?>
      </section>

      <section>
        <?php include_once 'version-info/v8.phtml'; ?>
      </section>

      <section>
        <?php include_once 'version-info/jsc.phtml'; ?>
      </section>

      <section>
        <?php include_once 'version-info/opera.phtml'; ?>
      </section>

      <section>
        <?php include_once 'version-info/actionscript.phtml'; ?>
      </section>

      <section>
        <?php include_once 'version-info/ecmascript.phtml'; ?>
      </section>