        <div>
          <h3><a name="actionscript" id="actionscript"
            >Macromedia/Adobe ActionScript</a><a
            href="#fn-actionscript"><sup>3)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            ActionScript versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>ActionScript&nbsp;1.0</th>
              <th>2.0</th>
              <th><a href="http://livedocs.adobe.com/specs/actionscript/3/wwhelp/wwhimpl/js/html/wwhelp.htm">3.0</a></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="9"><a name="fn-actionscript" id="fn-actionscript"
                >3)</a><a href="#actionscript" class="backref">&#8593;</a>
                Version information from
                <a href="http://macromedia.com/software/flash/">Macromedia</a> and
                <a href="https://en.wikipedia.org/wiki/ActionScript">Wikipedia</a></td>
            </tr>
          </tfoot>
          <tbody>
            <tr>
              <th><a href="http://macromedia.com/software/flash/">Macromedia
              Flash</a></th>
              <td>5.0–MX (2000/2003)</td>
              <td>7.1.1 (MX 2004) (2004/2006)</td>
            </tr>
            <tr>
              <th>Macromedia/Adobe Flash Player</a></th>
              <td>2–6 (1997/<span class="date">2002&#8208;03</span>)</td>
              <td>7–8 (<span class="date">2003&#8208;09</span>/<span class="date">2005&#8208;08</span>)</td>
              <td>9 (<span class="date">2006-06</span>)&#8212;</td>
            </tr>
            <tr>
              <th><a href="http://www.adobe.com/products/flex.html">Adobe Flex</a></th>
              <td colspan="2">&nbsp;</td>
              <td>2.0 (<span class="date">2006-06</span>)&#8212;</td>
            </tr>
          </tbody>
        </table>