        <div>
          <h3><a name="actionscript" id="actionscript"
            >Macromedia/Adobe&nbsp;ActionScript Versions</a><a
            href="#fn-actionscript"><sup>3)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            ActionScript versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>ActionScript&nbsp;1.0</th>
              <th>2.0</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="9"><a name="fn-actionscript" id="fn-actionscript"
                >3)</a><a href="#actionscript" class="backref">&#8593;</a>
                Version information from <a
                  href="http://macromedia.com/software/flash/"
                >Macromedia</a></td>
            </tr>
          </tfoot>
          <tbody>
            <tr>
              <th><a href="http://macromedia.com/software/flash/">Macromedia
              Flash</a></th>
              <td>5.0–MX (2000–2003)</td>
              <td>7.1.1 (MX 2004)&#8212; (2004&#8212;)</td>
            </tr>
          </tbody>
        </table>