        <div>
          <h3><a name="ecmascript" id="ecmascript">ECMAScript Compatibility</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>

          <p>The following table provides a rough overview of ECMAScript Editions
          and relations between them and versions of their implementations. Note
          that conforming implementations are allowed to <em>extend</em>
          ECMAScript, so these are <em>by no means</em> 1:n relations; instead,
          this is the result of a comparison of most common language features.</p>

          <p style="text-align: left">See <a href="#features">Language&nbsp;Features</a>
          above for details.</p>
        </div>

        <table class="versions">
          <caption>
            ECMAScript editions and versions of implementations that
            implement them best
          </caption>
          <thead>
            <tr>
              <td></td>
              <th>ECMAScript&nbsp;Edition&nbsp;1</th>
              <th>2</th>
              <th>3</th>
              <th>4<br>
              (Working&nbsp;Draft; abandoned)</th>
              <th>5</th>
              <th>6<br>
              ("Harmony", Working&nbsp;Draft)</th>
            </tr>
            <tr>
              <th></th>
              <td><a href="http://www.mozilla.org/js/language/">June&nbsp;1997</a></td>
              <td><a href="http://www.mozilla.org/js/language/">August&nbsp;1998</a></td>
              <td><a
                href="http://www.ecma-international.org/publications/standards/Ecma-262.htm"
              >December&nbsp;1999</a> –&nbsp;<a
                href="http://developer.mozilla.org/en/docs/JavaScript_Language_Resources#JavaScript_1.x"
              >March&nbsp;2000</a></td>
              <td><a href="http://www.ecmascript.org/">August&nbsp;2000
              –&nbsp;June&nbsp;2003 –&nbsp;2008</a></td>
              <td><a href="http://www.ecmascript.org/">April&nbsp;2009 –&nbsp;December&nbsp;2009</a></td>
              <td><a href="http://www.ecmascript.org/">April&nbsp;2009&#8212;</a></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="#actionscript">ActionScript</a></th>
              <td colspan="2"></td>
              <td>2.0 (2004)</td>
              <td>3.0 (2008&#8212;)</td>
            </tr>
            <tr>
              <th><a href="#javascript">JavaScript</a></th>
              <td>1.1, 1.3, 1.4</td>
              <td></td>
              <td>1.5–1.8.1.x</td>
              <td>2.0</td>
              <td>1.8.1&#8212; (2008-05&#8212;)</td>
            </tr>
            <tr>
              <th><a href="#jsc">JavaScriptCore</a></th>
            </tr>
            <tr>
              <th><a href="#jscript">JScript</a></th>
              <td>1.0 (1996)</td>
              <td></td>
              <td>5.5&#8212; (2000&#8212;)</td>
              <td>7.0&#8212; (2000&#8212;)</td>
            </tr>
            <tr>
              <th>KJS</th>
              <td colspan="2"></td>
              <td>1.0</td>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="http://www.opera.com/docs/specs/js/ecma/">Opera</a></th>
              <td colspan="2"></td>
              <td>6.0 (2001-12)</td>
            </tr>
            <tr>
              <th><a href="#v8">V8</a></th>
              <td colspan="2"></td>
              <td>0.3</td>
            </tr>
          </tbody>
        </table>

        <table class="versions" style="margin-top: 1em">
          <caption>
            Editions of ECMAScript for XML and implementations that
            implement them best
          </caption>
          <thead>
            <tr>
              <td></td>
              <th>ECMAScript&nbsp;for&nbsp;XML (E4X)</th>
            </tr>
            <tr>
              <td></td>
              <td><a
                href="http://www.ecma-international.org/publications/standards/Ecma-357.htm"
              >June&nbsp;2004</a></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="#actionscript">ActionScript</a></th>
              <td>2.0</td>
            </tr>
            <tr>
              <th><a href="#javascript">JavaScript</a></th>
              <td>1.6+</td>
            </tr>
            <tr>
              <th><a href="#jsc">JavaScriptCore</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="#jscript">JScript</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th>KJS</th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="http://www.opera.com/docs/specs/js/ecma/">Opera</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="#v8">V8</a></th>
              <td>-</td>
            </tr>
          </tbody>
        </table>