        <div>
          <h3><a name="ecmascript" id="ecmascript">ECMAScript Compatibility</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>

          <p>The following table provides a rough overview of ECMAScript Editions
          and relations between them and versions of their implementations. Note
          that conforming implementations are allowed to <em>extend</em>
          ECMAScript, so these are <em>by no means</em> 1:n relations; instead,
          this is the result of a comparison of most common language features.</p>

          <p style="text-align: left">See <a href="#features">Language&nbsp;Features</a>
          above for details.</p>
        </div>

        <table class="versions">
          <caption>
            ECMAScript editions and versions of implementations that
            implement them best
          </caption>
          <thead>
            <tr>
              <td></td>
              <th>ECMAScript&nbsp;Edition&nbsp;1</th>
              <th>2</th>
              <th>3</th>
              <th>4<br>
              (Working&nbsp;Draft; abandoned)</th>
              <th>5–5.1</th>
              <th>6<br>
              ("Harmony", Working&nbsp;Draft)</th>
            </tr>
            <tr>
              <th></th>
              <td><a href="http://www.mozilla.org/js/language/">1997&#8208;06</a></td>
              <td><a href="http://www.mozilla.org/js/language/">1998&#8208;08</a></td>
              <td><a
                href="http://www.ecma-international.org/publications/standards/Ecma-262.htm"
              >1999&#8208;12</a>/<a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Language_Resources"
              >2000&#8208;03</a></td>
              <td><a href="http://www.ecmascript.org/">2000&#8208;08/2003&#8208;06/2008</a></td>
              <td><a href="http://www.ecmascript.org/">2009&#8208;04/2009/12</a></td>
              <td><a href="http://www.ecmascript.org/">since 2009&#8208;04</a></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="#actionscript">ActionScript</a></th>
              <td colspan="2"></td>
              <td>2.0 (2004/2006)</td>
              <td>3.0 (2006)&#8212;</td>
            </tr>
            <tr>
              <th><a href="#javascript">JavaScript</a></th>
              <td>1.1, 1.3, 1.4</td>
              <td></td>
              <td>1.5–1.8.1.x</td>
              <td>2.0</td>
              <td>1.8.1–14 (2008&#8208;05/2012&#8208;07&#8208;17)</td>
              <td>15 (2012&#8208;08&#8208;28)&#8212;</td>
            </tr>
            <tr>
              <th><a href="#jsc">JavaScriptCore</a></th>
              <td>48–?</td>
              <td>?</td>
              <td>?</td>
              <td>&nbsp;</td>
              <td>528–537.70 (2009&#8208;08/2013)</td>
              <td>537.71 (2009&#8208;08)&#8212;</td>
            </tr>
            <tr>
              <th><a href="#jscript">JScript</a></th>
              <td>1.0 (1996)</td>
              <td></td>
              <td>5.5–5.7 (2000/2008&#8208;03)</td>
              <td>&nbsp;</td>
              <td>5.8 (2008&#8208;08)&#8212;</td>
            </tr>
            <tr>
              <th class="nowrap"><a href="#jscript">JScript .NET</a></th>
              <td colspan="3">&nbsp;</td>
              <td>7.0–10.0 (2000/2010)</td>
            </tr>
            <tr>
              <th>KJS</th>
              <td colspan="2"></td>
              <td>1.0</td>
              <td>&nbsp;</td>
              <td>4.6.5–</td>
            </tr>
            <tr>
              <th><a href="http://www.opera.com/docs/specs/js/ecma/">Opera</a></th>
              <td colspan="2"></td>
              <td>6.0 (2001-12)</td>
              <td>&nbsp;</td>
              <td>11.60–12.15 (<span class="date">2011&#8208;12&#8208;06</span>/<span class="date">2013&#8208;04&#8208;04</span>)</td>
            </tr>
            <tr>
              <th><a href="#v8">V8</a></th>
              <td colspan="2"></td>
              <td>0.3</td>
              <td>&nbsp;</td>
              <td>1.3.12–3.15.1 (2009&#8208;09&#8208;22/2012&#8208;11&#8208;06)</td>
              <td>3.15.2 (2012-11-12)&#8212;</td>
            </tr>
          </tbody>
        </table>

        <table class="versions" style="margin-top: 1em">
          <caption>
            Editions of ECMAScript for XML and implementations that
            implement them best
          </caption>
          <thead>
            <tr>
              <td></td>
              <th>ECMAScript&nbsp;for&nbsp;XML (E4X)</th>
            </tr>
            <tr>
              <td></td>
              <td><a
                href="http://www.ecma-international.org/publications/standards/Ecma-357.htm"
              >June&nbsp;2004</a></td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="#actionscript">ActionScript</a></th>
              <td>2.0–3</td>
            </tr>
            <tr>
              <th><a href="#javascript">JavaScript</a></th>
              <td>1.6–20</td>
            </tr>
            <tr>
              <th><a href="#jsc">JavaScriptCore</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="#jscript">JScript</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th class="nowrap"><a href="#jscript">JScript .NET</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th>KJS</th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="http://www.opera.com/docs/specs/js/ecma/">Opera</a></th>
              <td>-</td>
            </tr>
            <tr>
              <th><a href="#v8">V8</a></th>
              <td>-</td>
            </tr>
          </tbody>
        </table>