        <div>
          <h3><a name="javascript" id="javascript">Netscape/Mozilla JavaScript</a><a href="#fn-javascript"><sup>1)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            JavaScript versions and the user agents that support them
          </caption>
          <colgroup span="1">
          <colgroup span="27">
          <thead>
            <tr>
              <th scope="row" class="right">JavaScript</th>
              <th scope="col"><a
                href="http://e-pla.net/documents/manuals/javascript-1.0/"
                title="JavaScript Authoring Guide for JavaScript 1.0 (archived at e-pla.net)"
                >1.0</a></th>
              <th scope="col"><a
                href="http://web.archive.org/web/20020606113017/http://wp.netscape.com/eng/mozilla/3.0/handbook/javascript/"
                title="JavaScript Guide for JavaScript 1.1 (from the Internet Archive)"
                >1.1</a></th>
              <th scope="col">1.2</th>
              <th scope="col"><a
                href="http://wayback.archive.org/web/20040929030717/http://devedge.netscape.com/library/manuals/2000/javascript/1.3/reference/"
                title="Client-side JavaScript 1.3 Reference (from the Internet Archive)"
                >1.3</a></th>
              <th scope="col"><a
                href="http://wayback.archive.org/web/20040818025247/http://devedge.netscape.com/library/manuals/2000/javascript/1.4/reference/"
                title="Core JavaScript 1.4 Reference (from the Internet Archive)"
                >1.4</a></th>
              <th scope="col"><a href="http://replay.waybackmachine.org/20061205033609/http://www.mozilla.org/js/language/js20/"
                   >2.0</a> (historic)</th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference"
                title="Core JavaScript 1.5 Reference"
                >1.5</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/1.6"
                title="New in JavaScript 1.6"
                >1.6</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/1.7"
                title="New in JavaScript 1.7"
                >1.7</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/1.8"
                title="New in JavaScript 1.8"
                >1.8</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/1.8.1"
                title="New in JavaScript 1.8.1"
                >1.8.1</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/3.6#JavaScript"
                title="New in JavaScript 1.8.2"
                >1.8.2</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/1.8.5"
                title="New in JavaScript 1.8.5"
                >1.8.5</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/5#JavaScript"
                title="Firefox 5 for developers: JavaScript"
                >5</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/6#JavaScript"
                title="Firefox 6 for developers: JavaScript"
                >6</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/7#JavaScript"
                title="Firefox 7 for developers: JavaScript"
                >7</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/8#JavaScript"
                title="Firefox 8 for developers: JavaScript"
                >8</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/10#JavaScript"
                title="Firefox 10 for developers: JavaScript"
                >10</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/12#JavaScript"
                title="Firefox 12 for developers: JavaScript"
                >12</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/13#JavaScript"
                title="Firefox 13 for developers: JavaScript"
                >13</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/15#JavaScript"
                title="Firefox 15 for developers: JavaScript"
                >15</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/16#JavaScript"
                title="Firefox 16 for developers: JavaScript"
                >16</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/17#JavaScript"
                title="Firefox 17 for developers: JavaScript"
                >17</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/18#JavaScript"
                title="Firefox 18 for developers: JavaScript"
                >18</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/19#JavaScript"
                title="Firefox 19 for developers: JavaScript"
                >19</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/20#JavaScript"
                title="Firefox 20 for developers: JavaScript"
                >20</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/21#JavaScript"
                title="Firefox 21 for developers: JavaScript"
                >21</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/22#JavaScript"
                title="Firefox 22 for developers: JavaScript"
                >22</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/23#JavaScript"
                title="Firefox 23 for developers: JavaScript"
                >23</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/24#JavaScript"
                title="Firefox 24 for developers: JavaScript"
                >24</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/25#JavaScript"
                title="Firefox 25 for developers: JavaScript"
                >25</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/26#JavaScript"
                title="Firefox 26 for developers: JavaScript"
                >26</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/27#JavaScript"
                title="Firefox 27 for developers: JavaScript"
                >27</a></th>
              <th scope="col"><a
                href="https://developer.mozilla.org/en-US/Firefox/Releases/28#JavaScript"
                title="Firefox 28 for developers: JavaScript"
                >28</a></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="28"><a name="fn-javascript" id="fn-javascript"
                >1)</a><a href="#javascript" class="backref">&#8593;</a>
                Version information from the JavaScript Guides and References;
                release dates from <a href="about:">about:</a>&nbsp;documents,
                <a href="http://www.mozilla.org/releases/cvstags.html">mozilla.org</a>
                and <a href="http://en.wikipedia.org/wiki/Mozilla_Firefox#History"
                       >Wikipedia</a>.</td>
            </tr>
          </tfoot>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="35">Implementations</th>
            </tr>
            <tr>
              <th scope="row">Netscape Mocha</th>
              <td>1.0</td>
              <td>1.1</td>
            </tr>
            <tr>
              <th scope="row"><a href="http://www.mozilla.org/js/spidermonkey/"
                     >Netscape/Mozilla SpiderMonkey</a> (in C)</th>
              <td colspan="2">&nbsp;</td>
              <td>1.2</td>
              <td>1.3</td>
              <td>1.4</td>
              <td>&nbsp;</td>
              <td>1.5</td>
              <td>1.6</td>
              <td>1.7</td>
              <td>1.8</td>
              <td>1.8.1 (<a
                href="https://developer.mozilla.org/En/SpiderMonkey/Internals/Tracing_JIT"
                >TraceMonkey</a>)</td>
              <td>1.8.2</td>
              <td>1.8.5 (<a
                href="https://wiki.mozilla.org/JaegerMonkey">JägerMonkey</a>)</td>
              <td>5</td>
              <td>6</td>
              <td>7</td>
              <td>8</td>
              <td>10</td>
              <td>12</td>
              <td>13</td>
              <td>15</td>
              <td>16</td>
              <td>17</td>
              <td>18 (<a
                href="https://wiki.mozilla.org/IonMonkey">IonMonkey</a>)</td>
              <td>19</td>
              <td>20 (<a
                href="https://blog.mozilla.org/javascript/2013/04/05/the-baseline-compiler-has-landed/"
                >Baseline</a>)</td>
              <td>21</td>
              <td>22 (<a
                href="https://wiki.mozilla.org/Javascript:SpiderMonkey:OdinMonkey">OdinMonkey</a>)</td>
              <td>23</td>
              <td>24</td>
              <td>25</td>
              <td>26</td>
              <td>27</td>
              <td>28</td>
            </tr>
            <tr>
              <th scope="row"><a href="http://wayback.archive.org/web/20090201134254/http://www.mozilla.org/js/language/Epimetheus.html"
                     >Mozilla Epimetheus</a> (in C++)</th>
              <td colspan="5"></td>
              <td>+ (<span title="2002-12">2002</span>)</td>
            </tr>
            <tr>
              <th scope="row"><a href="http://www.mozilla.org/rhino/"
                     >Netscape/Mozilla Rhino</a> (in Java)</th>
              <td colspan="4"></td>
              <td>1.4R3 (<span title="1999-05-10">1999</span>)</td>
              <td>&nbsp;</td>
              <td><a href="http://www.mozilla.org/rhino/rhino15R1.html"
                     >1.5R1</a>–<a
                     href="http://www.mozilla.org/rhino/rhino15R5.html"
                     >1.5R5</a>
                (<span title="2000-09-10 /&nbsp;2004-03-25">2000/2004</span>)</td>
              <td><a href="http://www.mozilla.org/rhino/rhino16R1.html"
                     >1.6R1</a>–<a
                     href="https://developer.mozilla.org/en/New_in_Rhino_1.6R7"
                     >1.6R7</a>
                (<span title="2004-11-29 /&nbsp;2007-08-20">2004/2007</span>)</td>
              <td><a href="https://developer.mozilla.org/en/New_in_Rhino_1.7R1"
                     >1.7R1</a>–<a
                     href="https://developer.mozilla.org/en/New_in_Rhino_1.7R2"
                     >1.7R2</a>
                (<span title="2008-03-06/2009-03-22">2008/2009</span>)</td>
              <td><a href="https://developer.mozilla.org/en/New_in_Rhino_1.7R3"
                     >1.7R3</a>–<a href="https://developer.mozilla.org/en/New_in_Rhino_1.7R4"
                     >1.7R4</a>
                (<span class="date">2011&#8208;06&#8208;03</span>/
                <span class="date">2012&#8208;06&#8208;18</span>)</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="35">Layout Engines</th>
            </tr>
            <tr>
              <th scope="row"><a href="https://developer.mozilla.org/en/docs/Gecko">Netscape/Mozilla
                <abbr title="Next Generation Layout Engine">NGLayout</abbr>/Gecko</a></th>
              <td colspan="6"></td>
              <td>0.6–1.8a6</td>
              <td>1.8b1–1.8</td>
              <td>1.8.1</td>
              <td>1.9</td>
              <td>1.9.1</td>
              <td>1.9.2</td>
              <td>1.9.3, 2.0</td>
              <td>5.0</td>
              <td>6.0</td>
              <td>7.0</td>
              <td>8.0–9.0</td>
              <td>10.0–11.0</td>
              <td>12.0</td>
              <td>13.0–14.0</td>
              <td>15.0</td>
              <td>16.0</td>
              <td>17.0</td>
              <td>18.0</td>
              <td>19.0</td>
              <td>20.0</td>
              <td>21.0</td>
              <td>22</td>
              <td>23</td>
              <td>24</td>
              <td>25</td>
              <td>26</td>
              <td>27</td>
              <td>28</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="35">Web Browsers</th>
            </tr>
            <tr>
              <th scope="row"><a href="http://browser.netscape.com/">Netscape
                Navigator/Browser</a>&nbsp;<span
                title="Development discontinued">&#8224;</span></th>
              <td>Navigator 2.0&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1996-03">1996</span>)</td>
              <td>3.0&nbsp;<span title="End-of-life">&#8224;</span> (<span title="1996-08">1996</span>)</td>
              <td>4.0–4.05&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1997-06">1997</span>)</td>
              <td>4.06–4.8&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1998-08-17 /&nbsp;2002-08">1998/2002</span>)</td>
              <td colspan="2">&nbsp;</td>
              <td>Navigator&nbsp;6.x –&nbsp;Browser&nbsp;8.1.3&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2000-11-14 /&nbsp;2007-04-02">2000/2007</span>)</td>
              <td>-</td>
              <td>Navigator&nbsp;9.0b1 –&nbsp;9.0.0.6&nbsp;<span
                title="End-of-life">&#8224;</span><br>
              (<span title="2007-06-05 /&nbsp;2008-02-29">2007/2008</span>)</td>
            </tr>
            <tr>
              <th scope="row"><a href="http://www.mozilla.com/firefox/">Mozilla
                Phoenix/Firebird/Firefox</a></th>
              <td colspan="6"></td>
              <td>Phoenix&nbsp;0.1 –&nbsp;Firefox&nbsp;1.0.8&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2002-09-23/2006-04-13">2002/2006</span>)</td>
              <td>Firefox&nbsp;1.5a1–1.5.0.12&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2005-05-31/2006-05-26">2005/2007</span>)</td>
              <td>2.0b1–2.0.0.18&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2006-07-12/2008-11-12">2006/2008</span>)</td>
              <td>3.0a2–3.0.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2007-02-07/2010-03-30">2007/2010</span>)</td>
              <td>3.1a1–3.5.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2008&#8208;07&#8208;28/2011&#8208;04&#8208;28"
                       >2008/2011</span>)</td>
              <td>3.6a1–3.6.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2010&#8208;01&#8208;21/2011&#8208;07&#8208;11">2010/2011</span>)</td>
              <td>3.7a1–4.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2010&#8208;02&#8208;10/2011&#8208;04&#8208;28"
                       >2010/2011</span>)</td>
              <td>5.0–5.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8208;06&#8208;21/2011&#8208;07&#8208;11">2011</span>)</td>
              <td>6&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8208;08&#8208;16">2011</span>)</td>
              <td>7&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8208;09&#8208;27">2011</span>)</td>
              <td>8–9&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8208;11&#8208;08/2012&#8208;01&#8208;30">2011/2012</span>)</td>
              <td>10–11&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8208;01&#8208;31/2012&#8208;04&#8208;23">2012</span>)</td>
              <td>12&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8208;04&#8208;24">2012</span>)</td>
              <td>13–14&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8208;06&#8208;05/2012&#8208;08&#8208;14">2012</span>)</td>
              <td>15&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8208;08&#8208;14">2012</span>)</td>
              <td>16&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8208;10&#8208;09">2012</span>)</td>
              <td>17<br>
                (<span title="2012&#8208;11&#8208;20">2012</span>)</td>
              <td>18&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2013&#8208;01&#8208;08">2013</span>)</td>
              <td>19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2013&#8208;02&#8208;19">2013</span>)</td>
              <td>20.0–20.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span>
                (<span title="2013&#8208;04&#8208;02/2013&#8208;04&#8208;11)">2013</span>)</td>
              <td>21&nbsp;<span title="End-of-life"
                >&#8224;</span>
                (<span title="2013&#8208;05&#8208;14">2013</span>)</td>
              <td>22&nbsp;<span title="End-of-life"
                >&#8224;</span>
                (<span title="2013&#8208;06&#8208;25">2013</span>)</td>
              <td>23.0–23.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span> (<span class="date">2013&#8208;08&#8208;16</span>)</td>
              <td>24.0–24.4.0esr (<span class="date">2013&#8208;09&#8208;17</span>/
                <span class="date">2014&#8208;03&#8208;18</span>)</td>
              <td>25&nbsp;<span title="End-of-life"
                >&#8224;</span>
                (<span title="2013&#8208;10&#8208;29">2013</span>)</td>
              <td>26&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2013&#8208;12&#8208;10">2013</span>)</td>
              <td>27&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span class="date" title="2014&#8208;02&#8208;04">2014&#8208;02</span>)</td>
              <td>28<br>
                (<span class="date">2014&#8208;03&#8208;18</span>)</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="35">Other Clients</th>
            </tr>
            <tr>
              <th scope="row"><a href="http://www.mozilla.org/products/mozilla1.x/">Mozilla
                Application&nbsp;Suite</a>&nbsp;<span
                title="Development discontinued">&#8224;</span></th>
              <td colspan="6"></td>
              <td>0.6–1.8a6–1.7.13&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2000&#8208;12&#8208;06/2006&#8208;04&#8208;21">2000/2006</span>)</td>
              <td>1.8b1&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005&#8208;02&#8208;23">2005</span>)</td>
            </tr>
            <tr>
              <th scope="row"><a href="http://www.mozilla.org/projects/seamonkey/">Mozilla
              SeaMonkey</a></th>
              <td colspan="7"></td>
              <td>1.0a–1.0.9&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005&#8208;09&#8208;15/2007&#8208;05&#8208;30">2005/2007</span>)</td>
              <td>1.1a–1.1.19&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2006&#8208;08&#8208;30/2010&#8208;03&#8208;16">2006/2010</span>)</td>
              <td>&nbsp;</td>
              <td>2.0a1–2.0.12<br>
                (<span class="date">2008&#8208;10&#8208;05</span>/
                <span class="date">2011&#8208;03&#8208;02</span>)</td>
              <td>&nbsp;</td>
              <td>2.1a1–2.1<br>
                (<span class="date">2010&#8208;05&#8208;18</span>/
                <span class="date">2011&#8208;06&#8208;10</span>)</td>
              <td>2.2b1–2.2<br>
                (<span class="date">2011&#8208;06&#8208;22</span>/
                <span class="date">2011&#8208;07&#8208;07</span>)</td>
            </tr>
            <tr>
              <th scope="row"><a href="http://www.mozilla.com/thunderbird/">Mozilla
              Thunderbird</a></th>
              <td colspan="6"></td>
              <td>0.1–1.0.8&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2003&#8208;07&#8208;28/2006&#8208;04&#8208;21">2003/2006</span>)</td>
              <td>1.1a1–1.5.0.14&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005-06-02/2007-12-19">2005/2007</span>)</td>
              <td>2.0a1–2.0.0.24&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2006-07-28/2010-03-15">2006/2010</span>)</td>
              <td>3.0a1, 3.0a2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008-05-13, 2008-08-12">2008</span>)</td>
              <td>3.0a3–3.0.11&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008-10-14/2010-12-09">2008/2010</span>)</td>
              <td>3.1a1–3.1.12<br>
                (<span class="date">2010&#8208;02&#8208;03</span>/
                <span class="date">2011&#8208;08&#8208;16</span>)</td>
              <td>3.3a1–3.3a3<br>
                (<span class="date">2010&#8208;11&#8208;23</span>/
                <span class="date">2011&#8208;01&#8208;20</span>)</td>
              <td>5.0b1–5.0<br>
                (<span class="date">2011&#8208;06&#8208;02</span>/
                <span class="date">2011&#8208;06&#8208;28</span>)</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="35">Web Servers</th>
            </tr>
            <tr>
              <th scope="row"><a href="http://wp.netscape.com/enterprise/">Netscape
              Enterprise&nbsp;Server</a>/<br>
              <a href="http://en.wikipedia.org/wiki/iPlanet"
                title="Wikipedia: iPlanet"
              >iPlanet</a>&nbsp;Web&nbsp;Server/<br>
              <a href="http://en.wikipedia.org/wiki/Sun_ONE"
                title="Wikipedia: Sun ONE"
              >Sun&nbsp;ONE</a> Web&nbsp;Server/<br>
              <a href="http://www.sun.com/software/products/appsrvr/">Sun
              Java&nbsp;System Web&nbsp;Server</a></th>
              <td></td>
              <td>2.0</td>
              <td>3.0</td>
              <td></td>
              <td>4.0/<a href="http://docs.sun.com/source/816-5930-10/"
                title="iPlanet Web Server, Enterprise Edition Server-Side JavaScript 1.4 Guide"
                >4.1</a> (1999)</td>
              <td>&nbsp;</td>
              <td>6.0</td>
            </tr>
            <tr>
              <th scope="row"><a href="http://firecat.nihonsoft.org/"
                class="broken">NihonSoft firecat</a></th>
              <td colspan="4">&nbsp;</td>
              <td>1.0.x Beta4 (2008)</td>
            </tr>
          </tbody>
        </table>
