        <div>
          <h3><a name="javascript" id="javascript">Netscape/Mozilla&nbsp;JavaScript
            Version Information</a><a href="#fn-javascript"><sup>1)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            JavaScript versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th class="right">JavaScript</th>
              <th><a
                href="http://e-pla.net/documents/manuals/javascript-1.0/"
                title="JavaScript Authoring Guide for JavaScript 1.0"
                >1.0</a></th>
              <th><a
                href="http://web.archive.org/wp.netscape.com/eng/mozilla/3.0/handbook/javascript/"
                title="JavaScript Guide for JavaScript 1.1 (archived at the Internet Wayback Machine)"
                >1.1</a></th>
              <th><a
                href="http://research.nihonsoft.org/javascript/jsref/"
                title="Client-side JavaScript 1.2 Reference (archived at Nihonsoft Research)"
                >1.2</a></th>
              <th><a
                href="http://research.nihonsoft.org/javascript/ClientReferenceJS13/"
                title="Client-side JavaScript 1.3 Reference (archived at Nihonsoft Research)"
                >1.3</a></th>
              <th><a
                href="http://research.nihonsoft.org/javascript/CoreReferenceJS14/"
                title="Core JavaScript 1.4 Reference (archived at Nihonsoft Research)"
                >1.4</a></th>
              <th><a href="http://replay.waybackmachine.org/20061205033609/http://www.mozilla.org/js/language/js20/"
                   >2.0</a> (historic)</th>
              <th><a
                href="http://developer.mozilla.org/en/docs/Core_JavaScript_1.5_Reference"
                title="Core JavaScript 1.5 Reference"
                >1.5</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.6"
                title="New in JavaScript 1.6"
                >1.6</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.7"
                title="New in JavaScript 1.7"
                >1.7</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.8"
                title="New in JavaScript 1.8"
                >1.8</a></th>
              <th><a
                href="http://developer.mozilla.org/en/docs/New_in_JavaScript_1.8.1"
                title="New in JavaScript 1.8.1"
                >1.8.1</a></th>
              <th><a
                href="https://developer.mozilla.org/En/Firefox_3.6_for_developers#JavaScript"
                title="New in JavaScript 1.8.2"
                >1.8.2</a></th>
              <th><a
                href="https://developer.mozilla.org/en/JavaScript/New_in_JavaScript/1.8.5"
                title="New in JavaScript 1.8.5"
                >1.8.5</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_5_for_developers#JavaScript"
                title="Firefox 5 for developers: JavaScript"
                >5</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_6_for_developers#JavaScript"
                title="Firefox 6 for developers: JavaScript"
                >6</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_7_for_developers#JavaScript"
                title="Firefox 7 for developers: JavaScript"
                >7</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_8_for_developers#JavaScript"
                title="Firefox 8 for developers: JavaScript"
                >8</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_10_for_developers#JavaScript"
                title="Firefox 10 for developers: JavaScript"
                >10</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_12_for_developers#JavaScript"
                title="Firefox 12 for developers: JavaScript"
                >12</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_13_for_developers#JavaScript"
                title="Firefox 13 for developers: JavaScript"
                >13</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_15_for_developers#JavaScript"
                title="Firefox 15 for developers: JavaScript"
                >15</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_16_for_developers#JavaScript"
                title="Firefox 16 for developers: JavaScript"
                >16</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_17_for_developers#JavaScript"
                title="Firefox 17 for developers: JavaScript"
                >17</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_18_for_developers#JavaScript"
                title="Firefox 18 for developers: JavaScript"
                >18</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_19_for_developers#JavaScript"
                title="Firefox 19 for developers: JavaScript"
                >19</a></th>
              <th><a
                href="https://developer.mozilla.org/en/Firefox_20_for_developers#JavaScript"
                title="Firefox 20 for developers: JavaScript"
                >20</a></th>
              <th><a
                href="https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/21#JavaScript"
                title="Firefox 21 for developers: JavaScript"
                >21</a></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="28"><a name="fn-javascript" id="fn-javascript"
                >1)</a><a href="#javascript" class="backref">&#8593;</a>
                Version information from the JavaScript Guides and References;
                release dates from <a href="about:">about:</a>&nbsp;documents,
                <a href="http://www.mozilla.org/releases/cvstags.html">mozilla.org</a>
                and <a href="http://en.wikipedia.org/wiki/Mozilla_Firefox#History"
                       >Wikipedia</a>.</td>
            </tr>
          </tfoot>
          <tbody>
            <tr class="header">
              <th colspan="28">Implementations</th>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/js/spidermonkey/"
                     >Netscape/Mozilla SpiderMonkey</a> (in C)</th>
              <td>1.0</td>
              <td>1.1</td>
              <td>1.2</td>
              <td>1.3</td>
              <td>1.4</td>
              <td>&nbsp;</td>
              <td>1.5</td>
              <td>1.6</td>
              <td>1.7</td>
              <td>1.8</td>
              <td>1.8.1 (<a
                href="https://developer.mozilla.org/En/SpiderMonkey/Internals/Tracing_JIT"
                >TraceMonkey</a>)</td>
              <td>1.8.2</td>
              <td>1.8.5 (<a
                href="https://wiki.mozilla.org/JaegerMonkey">JägerMonkey</a>)</td>
              <td>5</td>
              <td>6</td>
              <td>7</td>
              <td>8</td>
              <td>10</td>
              <td>12</td>
              <td>13</td>
              <td>15</td>
              <td>16</td>
              <td>17</td>
              <td>18 (<a
                href="https://wiki.mozilla.org/IonMonkey">IonMonkey</a>)</td>
              <td>19</td>
              <td>20</td>
              <td>21</td>
            </tr>
            <tr>
              <th><a href="http://wayback.archive.org/web/20090201134254/http://www.mozilla.org/js/language/Epimetheus.html"
                     >Mozilla Epimetheus</a> (in C++)</th>
              <td colspan="5"></td>
              <td>+ (<span title="2002-12">2002</span>)</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/rhino/"
                     >Netscape/Mozilla Rhino</a> (in Java)</th>
              <td colspan="4"></td>
              <td>1.4R3 (<span title="1999-05-10">1999</span>)</td>
              <td>&nbsp;</td>
              <td><a href="http://www.mozilla.org/rhino/rhino15R1.html"
                     >1.5R1</a>–<a
                     href="http://www.mozilla.org/rhino/rhino15R5.html"
                     >1.5R5</a>
                (<span title="2000-09-10 –&nbsp;2004-03-25">2000–2004</span>)</td>
              <td><a href="http://www.mozilla.org/rhino/rhino16R1.html"
                     >1.6R1</a>–<a
                     href="https://developer.mozilla.org/en/New_in_Rhino_1.6R7"
                     >1.6R7</a>
                (<span title="2004-11-29 –&nbsp;2007-08-20">2004–2007</span>)</td>
              <td><a href="https://developer.mozilla.org/en/New_in_Rhino_1.7R1"
                     >1.7R1</a>–<a
                     href="https://developer.mozilla.org/en/New_in_Rhino_1.7R2"
                     >1.7R2</a>
                (<span title="2008-03-06 –&nbsp;2009-03-22">2008–2009</span>)</td>
              <td><a href="https://developer.mozilla.org/en/New_in_Rhino_1.7R3"
                     >1.7R3</a>
                (2011&#8209;06&#8209;03)</td>
            </tr>

            <tr class="header">
              <th colspan="28">Layout Engines</th>
            </tr>
            <tr>
              <th><a href="https://developer.mozilla.org/en/docs/Gecko">Netscape/Mozilla
              <abbr title="Next Generation Layout Engine">NGLayout</abbr>/Gecko</a></th>
              <td colspan="6"></td>
              <td>0.6–1.8a6</td>
              <td>1.8b1–1.8</td>
              <td>1.8.1</td>
              <td>1.9</td>
              <td>1.9.1</td>
              <td>1.9.2</td>
              <td>1.9.3, 2.0</td>
              <td>5.0</td>
              <td>6.0</td>
              <td>7.0</td>
              <td>8.0–9.0</td>
              <td>10.0–11.0</td>
              <td>12.0</td>
              <td>13.0–14.0</td>
              <td>15.0</td>
              <td>16.0</td>
              <td>17.0</td>
              <td>18.0</td>
              <td>19.0</td>
              <td>20.0</td>
              <td>21.0</td>
            </tr>

            <tr class="header">
              <th colspan="28">Web Browsers</th>
            </tr>
            <tr>
              <th><a href="http://browser.netscape.com/">Netscape
                Navigator/Browser</a>&nbsp;<span
                title="Development discontinued">&#8224;</span></th>
              <td>Navigator 2.0&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1996-03">1996</span>)</td>
              <td>3.0&nbsp;<span title="End-of-life">&#8224;</span> (<span title="1996-08">1996</span>)</td>
              <td>4.0–4.05&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1997-06">1997</span>)</td>
              <td>4.06–4.8&nbsp;<span title="End-of-life">&#8224;</span>
                (<span title="1998-08-17 –&nbsp;2002-08">1998–2002</span>)</td>
              <td colspan="2">&nbsp;</td>
              <td>Navigator&nbsp;6.x –&nbsp;Browser&nbsp;8.1.3&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2000-11-14 –&nbsp;2007-04-02">2000–2007</span>)</td>
              <td>-</td>
              <td>Navigator&nbsp;9.0b1 –&nbsp;9.0.0.6&nbsp;<span
                title="End-of-life">&#8224;</span><br>
              (<span title="2007-06-05 –&nbsp;2008-02-29">2007–2008</span>)</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.com/firefox/">Mozilla
                Phoenix/Firebird/Firefox</a></th>
              <td colspan="6"></td>
              <td>Phoenix&nbsp;0.1 –&nbsp;Firefox&nbsp;1.0.8&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2002-09-23 –&nbsp;2006-04-13">2002–2006</span>)</td>
              <td>Firefox&nbsp;1.5a1–1.5.0.12&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span title="2005-05-31 –&nbsp;2006-05-26">2005–2007</span>)</td>
              <td>2.0b1–2.0.0.18&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2006-07-12 –&nbsp;2008-11-12">2006–2008</span>)</td>
              <td>3.0a2–3.0.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2007-02-07 –&nbsp;2010-03-30">2007–2010</span>)</td>
              <td>3.1a1–3.5.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2008&#8209;07&#8209;28 –&nbsp;2011&#8209;04&#8209;28"
                       >2008–2011</span>)</td>
              <td>3.6a1–3.6.19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2010&#8209;01&#8209;21 –&nbsp;2011&#8209;07&#8209;11">2010–2011</span>)</td>
              <td>3.7a1–4.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2010&#8209;02&#8209;10 –&nbsp;2011&#8209;04&#8209;28"
                       >2010–2011</span>)</td>
              <td>5.0–5.0.1&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;06&#8209;21 –&nbsp;2011&#8209;07&#8209;11">2011</span>)</td>
              <td>6&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;08&#8209;16">2011</span>)</td>
              <td>7&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;09&#8209;27">2011</span>)</td>
              <td>8–9&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2011&#8209;11&#8209;08 –&nbsp;2012&#8209;01&#8209;30">2011–2012</span>)</td>
              <td>10–11&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;01&#8209;31 –&nbsp;2012&#8209;04&#8209;23">2012</span>)</td>
              <td>12&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;04&#8209;24">2012</span>)</td>
              <td>13–14&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;06&#8209;05 –&nbsp;2012&#8209;08&#8209;14">2012</span>)</td>
              <td>15&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;08&#8209;14">2012</span>)</td>
              <td>16&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2012&#8209;10&#8209;09">2012</span>)</td>
              <td>17<br>
                (<span title="2012&#8209;11&#8209;20">2012</span>)</td>
              <td>18&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2013&#8209;01&#8209;08">2013</span>)</td>
              <td>19&nbsp;<span title="End-of-life"
                >&#8224;</span><br>
                (<span title="2013&#8209;02&#8209;19">2013</span>)</td>
              <td>20<br>
                (<span title="2013&#8209;04&#8209;02">2013&#8209;04&#8209;02</span>)</td>
              <td>21<br>
                (<span title="2013&#8209;05&#8209;14">2013&#8209;05&#8209;14</span>)</td>
            </tr>

            <tr class="header">
              <th colspan="28">Other Clients</th>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/products/mozilla1.x/">Mozilla
                Application&nbsp;Suite</a>&nbsp;<span
                title="Development discontinued">&#8224;</span></th>
              <td colspan="6"></td>
              <td>0.6–1.8a6–1.7.13&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2000-12-06 –&nbsp;2006-04-21">2000–2006</span>)</td>
              <td>1.8b1&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005-02-23">2005</span>)</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.org/projects/seamonkey/">Mozilla
              SeaMonkey</a></th>
              <td colspan="7"></td>
              <td>1.0a–1.0.9&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005-09-15 –&nbsp;2007-05-30">2005–2007</span>)</td>
              <td>1.1a–1.1.19&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2006-08-30 –&nbsp;2010-03-16">2006–2010</span>)</td>
              <td>&nbsp;</td>
              <td>2.0a1–2.0.12<br>
                (2008&#8209;10&#8209;05 –&nbsp;2011&#8209;03&#8209;02)</td>
              <td>&nbsp;</td>
              <td>2.1a1–2.1<br>
                (2010&#8209;05&#8209;18 –&nbsp;2011&#8209;06&#8209;10)</td>
              <td>2.2b1–2.2<br>
                (2011&#8209;06&#8209;22 –&nbsp;2011&#8209;07&#8209;07)</td>
            </tr>
            <tr>
              <th><a href="http://www.mozilla.com/thunderbird/">Mozilla
              Thunderbird</a></th>
              <td colspan="6"></td>
              <td>0.1–1.0.8&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2003-07-28 –&nbsp;2006-04-21">2003–2006</span>)</td>
              <td>1.1a1–1.5.0.14&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005-06-02 –&nbsp;2007-12-19">2005–2007</span>)</td>
              <td>2.0a1–2.0.0.24&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2006-07-28 –&nbsp;2010-03-15">2006–2010</span>)</td>
              <td>3.0a1, 3.0a2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008-05-13, 2008-08-12">2008</span>)</td>
              <td>3.0a3–3.0.11&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008-10-14 –&nbsp;2010-12-09">2008–2010</span>)</td>
              <td>3.1a1–3.1.12<br>
                (2010&#8209;02&#8209;03 –&nbsp;2011&#8209;08&#8209;16)</td>
              <td>3.3a1–3.3a3<br>
                (2010&#8209;11&#8209;23 –&nbsp; 2011&#8209;01&#8209;20)</td>
              <td>5.0b1–5.0<br>
                (2011&#8209;06&#8209;02 –&nbsp;2011&#8209;06&#8209;28)</td>
            </tr>

            <tr class="header">
              <th colspan="28">Web Servers</th>
            </tr>
            <tr>
              <th><a href="http://wp.netscape.com/enterprise/">Netscape
              Enterprise&nbsp;Server</a>/<br>
              <a href="http://en.wikipedia.org/wiki/iPlanet"
                title="Wikipedia: iPlanet"
              >iPlanet</a>&nbsp;Web&nbsp;Server/<br>
              <a href="http://en.wikipedia.org/wiki/Sun_ONE"
                title="Wikipedia: Sun ONE"
              >Sun&nbsp;ONE</a> Web&nbsp;Server/<br>
              <a href="http://www.sun.com/software/products/appsrvr/">Sun
              Java&nbsp;System Web&nbsp;Server</a></th>
              <td></td>
              <td>2.0</td>
              <td>3.0</td>
              <td></td>
              <td>4.0/<a href="http://docs.sun.com/source/816-5930-10/"
                title="iPlanet Web Server, Enterprise Edition Server-Side JavaScript 1.4 Guide"
              >4.1</a> (1999)</td>
              <td>&nbsp;</td>
              <td>6.0</td>
            </tr>
            <tr>
              <th><a href="http://firecat.nihonsoft.org/">NihonSoft
              firecat</a></th>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>1.0.x Beta4 (2008)</td>
            </tr>
          </tbody>
        </table>