        <div>
          <h3><a name="jsc" id="jsc">Apple&nbsp;JavaScriptCore Version
            Information</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            Apple JavaScriptCore versions and the user agents that
            support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th><abbr title="JavaScriptCore">JSC</abbr>&nbsp;48–312.6</th>
              <th>412–419.13</th>
              <th><span title="522.11–523.10">522–523</span></th>
              <th>525.13–525.20</th>
              <th>525.19–525.21</th>
              <th>525.27–525.28</th>
              <th>530.17–530.19</th>
              <th>531.9</th>
              <th><span title="531.21.8–531.21.10">531.21</span></th>
              <th>531.22.7</th>
              <th>533.16–<span title="533.19.4">533.19</span></th>
              <th>533.16–<span title="534.48.3">534.48</span></th>
              <th><span title="534.51.22–534.53.10">534.51–534.53</span></th>
              <th><span title="534.54.16–534.59.10">534.54–534.59</span></th>
              <th>536.25–<span title="537.73.11">537.73</span></th>
              <th>537.71–<span title="537.73.11">537.73</span></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="http://apple.com/safari/">Apple Safari</a></th>
              <td>0.8–1.3.2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2003&#8208;01&#8208;07/2006&#8208;01&#8208;12">2003/2006</span>&nbsp;<a
                href="http://en.wikipedia.org/wiki/Common_Era"
                ><abbr title="Common Era">CE</abbr></a>)</td>
              <td><span title="2.0–2.0.4">2.0.x</span>&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2005&#8208;04&#8208;29/2006&#8208;01&#8208;10">2005/2006</span>)</td>
              <td><span title="3.0–3.0.4">3.0.x</span>&nbsp;<span title="End-of-life">&#8224;</span><br>
                 (<span title="2007&#8208;06/2007&#8208;10">2007</span>)</td>
              <td>3.1–3.1.1&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008&#8208;03&#8208;18/2008&#8208;05&#8208;28">2008</span>)</td>
              <td>3.1.2–3.2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008&#8208;06&#8208;30/2008&#8208;11&#8208;13">2008</span>)</td>
              <td>3.2.1–3.2.3&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2008&#8208;11&#8208;24/2009&#8208;05&#8208;12">2008/2009</span>)</td>
              <td>4.0–4.0.2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2009&#8208;06&#8208;08/2009&#8208;07&#8208;08">2009</span>)</td>
              <td>4.0.3&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2009&#8208;08&#8208;11">2009</span>)</td>
              <td>4.0.4&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2009&#8208;11&#8208;11">2009</span>)</td>
              <td>4.0.5&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2010&#8208;03&#8208;11">2010</span>)</td>
              <td><span title="4.1–4.1.3">4.1.x</span>&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2010&#8208;06&#8208;07/2010&#8208;11&#8208;08">2010</span>)</td>
              <td>5.0–5.1&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2010&#8208;06&#8208;07/2011&#8208;07&#8208;20">2010/2011</span>)</td>
              <td>5.1.1–5.1.3&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2011&#8208;10&#8208;12/2012&#8208;02&#8208;01">2011/2012</span>)</td>
              <td>5.1.4–5.1.10&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span title="2012&#8208;03&#8208;12/2013&#8208;09&#8208;12">2012/2013</span>)</td>
              <td>6.0–6.1.1<br>
                (<span class="nowrap">2012&#8208;07&#8208;25</span>/
                <span class="nowrap">2013&#8208;12&#8208;16</span>)</td>
              <td>7.0–7.0.1<br>
                (<span class="nowrap">2013&#8208;10&#8208;22</span>/
                <span class="nowrap">2013&#8208;12&#8208;16</span>)</td>
            </tr>
          </tbody>
        </table>