        <div>
          <h3><a name="jsc" id="jsc">Apple&nbsp;JavaScriptCore Version
            Information</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            Apple JavaScriptCore versions and the user agents that
            support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>JavaScriptCore&nbsp;48–312.6</th>
              <th>412–419.13</th>
              <th>522.11–523.10</th>
              <th>525.13</th>
              <th>525.19</th>
              <th>525.27.1</th>
              <th>530.17</th>
              <th>531.9</th>
              <th>531.21.8</th>
              <th>531.22.7</th>
              <th>533.16</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="http://apple.com/safari/">Apple Safari</a></th>
              <td>0.8–1.3.2&nbsp;<span title="End-of-life">&#8224;</span><br>
                (2003–2006&nbsp;<a
                href="http://en.wikipedia.org/wiki/Common_Era"
                ><abbr title="Common Era">CE</abbr></a>)</td>
              <td>2.0–2.0.4<br>
                (2005-04 –&nbsp;2006-01)</td>
              <td>3.0–3.0.4<br>
                 (2007-06 –&nbsp;2007-10)</td>
              <td>3.1<br>
                (2008-03)</td>
              <td>3.1.2<br>
                (2008-06)</td>
              <td>3.2.1<br>
                (2008-11)</td>
              <td>4.0<br>
                (2009-06)</td>
              <td>4.0.3<br>
                (2009-08)</td>
              <td>4.0.4<br>
                (2009-11)</td>
              <td>4.0.5<br>
                (2010-03-11)</td>
              <td>5.0<br>
                (2010-06-07)</td>
            </tr>
          </tbody>
        </table>