        <div>
          <h3><a name="jscript" id="jscript">Microsoft&nbsp;JScript Version
            Information</a><a href="#fn-jscript"><sup>2)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            JScript versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th class="right">JScript</th>
              <th>1.0</th>
              <th>2.0</th>
              <th>3.0</th>
              <th>3.1.3510</th>
              <th>4.0</th>
              <th>5.0</th>
              <th>5.1.5010</th>
              <th>5.5.6330</th>
              <th><a
                href="http://msdn2.microsoft.com/en-us/library/hbxc2t98.aspx"
                title="JScript 5.6 documentation"
              >5.6.6626</a> –&nbsp;5.6.8819</th>
              <th>5.7.5730</th>
              <th>5.7.17184</th>
              <th>5.8.18241</th>
              <th>7.0 (.NET)</th>
              <th><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a%28VS.71%29.aspx"
                title="JScript 7.1 (.NET) documentation"
              >7.1 (.NET)</a></th>
              <th><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a%28VS.80%29.aspx"
                title="JScript 8.0 documentation"
              >8.0</a></th>
              <th>9.0.16421
               (<a href="http://en.wikipedia.org/wiki/Chakra_(JavaScript_engine)"
                   >Chakra</a>)</th>
              <th><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a.aspx"
                title="JScript 10.0 documentation"
              >10.0</a></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="16"><a name="fn-jscript" id="fn-jscript"
                >2)</a><a href="#jscript" class="backref">&#8593;</a>
                Version information from <a
                  href="http://msdn.microsoft.com/library/en-us/jscript7/html/jsoriVersionInformation.asp"
                ><abbr title="Microsoft Developer Network">MSDN</abbr>&nbsp;Library</a>;
                release&nbsp;dates from MSDN&nbsp;Library, <a
                  href="http://www.blooberry.com/indexdot/history/ie.htm"
                  title="Browser History: Windows Internet Explorer"
                >blooberry.com</a> and <a href="http://en.wikipedia.org/">Wikipedia</a>,
                end-of-life&nbsp;(&#8224;) dates from <a
                 href="http://support.microsoft.com/gp/lifeselectindex"
                  >support.microsoft.com</a>.<br>
                <em>Note that the language version supported by an environment
                may be greater than specified here due to security updates.
                When in doubt, use the <a href="#script-engine-test"
                >script engine test above</a> to determine the true version.</em>
              </td>
            </tr>
          </tfoot>
          <tbody>
            <tr class="header">
              <th colspan="18">Implementations</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/net/">Microsoft .NET Framework</a></th>
              <td colspan="12"></td>
              <td>1.0 (2002-01)</td>
              <td>1.1 (2003)</td>
              <td>2.0–3.5&nbsp;SP1 (2005–2008)</td>
              <td></td>
              <td>4.0&#8212; (2010-04-12&#8212;)</td>
            </tr>

            <tr class="header">
              <th colspan="18">Web Browsers</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/ie/">Microsoft Internet Explorer</a></th>
              <td>3.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1996-08</span> <a
                href="http://en.wikipedia.org/wiki/Common_Era"
              ><abbr title="Common Era">CE</abbr></a>)</td>
              <td></td>
              <td class="nowrap">4.0 <span title="End-of-life">&#8224;</span><br>
                (1997-09)</td>
              <td class="nowrap">4.01 <span title="End-of-life">&#8224;</span><br>
              	(1997-11)</td>
              <td></td>
              <td>5.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1999-03</span>
                <span class="nowrap">– 2005-06)</span></td>
              <td class="nowrap">5.01 <span title="End-of-life">&#8224;</span></td>
              <td>5.5&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000-07</span>
                <span class="nowrap">–&nbsp;2005-12)</span></td>
              <td>6.0 for <abbr title="Windows 95 and 98">Win9x</abbr>/NT/XP&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2001-10)</span></td>
              <td>7.0 for <abbr title="Windows">Win</abbr>XP+<br>
                <span class="nowrap">(2006-10)</span></td>
              <td>8.0 beta 1 for <abbr title="Windows">Win</abbr>XP SP2+<br>
                <span class="nowrap">(2008-03)</span></td>
              <td>8.0 beta&nbsp;2 for <abbr title="Windows">Win</abbr>XP SP2+<br>
                <span class="nowrap">(2008-08)</span></td>
              <td colspan="3"></td>
              <td><span title="9.0.8112.16421">9.0</span> for Vista SP2+ / Server&nbsp;2008<br>
                (2011&#8209;03&#8209;14)</td>
            </tr>

            <tr class="header">
              <th colspan="18">Web Servers</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/iis/">Microsoft Internet
              Information Server/Services</a></th>
              <td colspan="2"></td>
              <td>4.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1998–2002)</span></td>
              <td colspan="5"></td>
              <td>5.1–6.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000–2005)</span></td>
              <td colspan="2">7.0<br>
                <span class="nowrap">(2008)</span></td>
              <td>7.5<br>
                <span class="nowrap">(2009)</span></td>
            </tr>

            <tr class="header">
              <th colspan="18">Operating Systems</th>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/windows/">Microsoft Windows</a></th>
              <td></td>
              <td>NT&nbsp;4.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1996)</span></td>
              <td colspan="4"></td>
              <td>2000&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000-02</span>
                <span class="nowrap">–&nbsp;2005-06)</span></td>
              <td><abbr title="Millennium Edition">Me</abbr>&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(2000-09</span>
                <span class="nowrap">–&nbsp;2005-12)</span></td>
              <td><abbr title="eXPeriment^H^H^H^Hence ;-)">XP</abbr><br>
                <span class="nowrap">(2001-10)</span></td>
              <td colspan="2">Vista<br>
                <span class="nowrap">(2008-03)</span></td>
              <td>7<br>
                <span class="nowrap">(2009-10)</span></td>
            </tr>
            <tr>
              <th><a href="http://microsoft.com/windowsserver2003/"
                     >Microsoft Windows Server</a></th>
              <td colspan="8"></td>
              <td>2003<br>
                <span class="nowrap">(2003-04)</span></td>
              <td colspan="2">2008<br>
                <span class="nowrap">(2008-02)</span></td>
              <td>2008&nbsp;R2<br>
                <span class="nowrap">(2009-09)</span></td>
              <td colspan="2">&nbsp;</td>
              <td>2008</td>
              <td>&nbsp;</td>
              <td>2008&nbsp;R2</td>
            </tr>

            <tr class="header">
              <th colspan="18"><abbr
                title="Integrated Development Environment"
              >IDE</abbr>s</th>
            </tr>
            <tr>
              <th><a href="http://www.microsoft.com/visualstudio/en-us/products"
                     >Microsoft Visual Studio</a></th>
              <td colspan="4"></td>
              <td>6.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                <span class="nowrap">(1998–2005)</span></td>
              <td colspan="7"></td>
              <td>.NET&nbsp;7.0<br>(2002)</td>
              <td>.NET&nbsp;7.1<br>(2003)</td>
              <td>8.0–9.0<br>(2005–2008)</td>
              <td></td>
              <td>10.0&#8212;<br>(2010-04-12&#8212;)</td>
            </tr>
          </tbody>
        </table>