        <div>
          <h3><a name="jscript" id="jscript">Microsoft JScript</a><a href="#fn-jscript"><sup>2)</sup></a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            JScript versions and the user agents that support them
          </caption>
          <colgroup span="1"/>
          <colgroup span="19"/>
          <thead>
            <tr>
              <th scope="row" class="right">JScript</th>
              <th scope="col" id="jscript1.0">1.0</th>
              <th scope="col" id="jscript2.0">2.0</th>
              <th scope="col" id="jscript3.0">3.0</th>
              <th scope="col" id="jscript3.1">3.1.3510</th>
              <th scope="col" id="jscript4.0">4.0</th>
              <th scope="col" id="jscript5.0">5.0</th>
              <th scope="col" id="jscript5.1">5.1.5010</th>
              <th scope="col" id="jscript5.5">5.5.6330</th>
              <th scope="col" id="jscript5.6"><a
                href="http://msdn2.microsoft.com/en-us/library/hbxc2t98.aspx"
                title="JScript 5.6 documentation"
              >5.6.6626</a>–5.6.8819</th>
              <th scope="col" id="jscript5.7.5730">5.7.5730</th>
              <th scope="col" id="jscript5.7.17184">5.7.17184</th>
              <th scope="col" id="jscript5.8">5.8.18241</th>
              <td colspan="3">&nbsp;</td>
              <th scope="col" id="jscript9.0">9.0.16421
               (<a href="http://en.wikipedia.org/wiki/Chakra_(JavaScript_engine)"
                   >Chakra</a>)</th>
              <td>&nbsp;</td>
              <th scope="col" id="jscript10.0"><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a.aspx"
                title="JScript 10.0 documentation"
              >10.0.16578</a></th>
              <th scope="col" id="jscript11.0"><a
                href="http://msdn.microsoft.com/en-us/library/d1et7k7c(v=vs.94).aspx"
                title="JScript 11.0 documentation"
              >11</a></th>
            </tr>
            <tr>
              <th scope="row" class="right">JScript .NET</th>
              <td colspan="12">&nbsp;</td>
              <th scope="col" id="jscript.net7.0">7.0 (.NET)</th>
              <th scope="col" id="jscript.net7.1"><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a%28VS.71%29.aspx"
                title="JScript 7.1 (.NET) documentation"
                >7.1 (.NET)</a></th>
              <th scope="col" id="jscript.net8.0"><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a%28VS.80%29.aspx"
                title="JScript .NET 8.0 documentation"
                >8.0</a></th>
              <td>&nbsp;</td>
              <th scope="col" id="jscript.net10.0"><a
                href="http://msdn.microsoft.com/en-us/library/72bd815a.aspx"
                title="JScript .NET 10.0 documentation"
              >10.0</a></th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <td colspan="16"><a name="fn-jscript" id="fn-jscript"
                >2)</a><a href="#jscript" class="backref">&#8593;</a>
                Version information from <a
                  href="http://msdn.microsoft.com/en-us/library/2z6exc9e(v=vs.100).aspx"
                  ><abbr title="Microsoft Developer Network">MSDN</abbr>&nbsp;Library</a>;
                release&nbsp;dates from MSDN&nbsp;Library, <a
                  href="http://www.blooberry.com/indexdot/history/ie.htm"
                  title="Browser History: Windows Internet Explorer"
                >blooberry.com</a> and <a href="http://en.wikipedia.org/">Wikipedia</a>,
                end-of-life&nbsp;(&#8224;) dates from <a
                 href="http://support.microsoft.com/gp/lifeselectindex"
                  >support.microsoft.com</a>.<br>
                <em>Note that the language version supported by an environment
                may be greater than specified here due to security updates.
                When in doubt, use the <a href="#script-engine-test"
                >script engine test above</a> to determine the true version.</em>
              </td>
            </tr>
          </tfoot>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="20">Implementations</th>
            </tr>
            <tr>
              <th scope="row" id=".net"><a href="http://microsoft.com/net/">Microsoft .NET Framework</a></th>
              <td colspan="12"></td>
              <td headers=".net jscript.net7.0">1.0 (2002&#8208;01)</td>
              <td headers=".net jscript.net7.1">1.1 (2003)</td>
              <td headers=".net jscript.net8.0">2.0–3.5&nbsp;SP1 (2005/2008)</td>
              <td>&nbsp;</td>
              <td headers=".net jscript.net10.0">4.0 (<span class="date">2010&#8208;04&#8208;12</span>)</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="20">Web Browsers</th>
            </tr>
            <tr>
              <th scope="row" id="ie"><a href="http://microsoft.com/ie/">Microsoft Internet Explorer</a></th>
              <td headers="ie jscript1.0">3.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">1996&#8208;08</span> <a
                href="http://en.wikipedia.org/wiki/Common_Era"
              ><abbr title="Common Era">CE</abbr></a>)</td>
              <td></td>
              <td headers="ie jscript3.0" class="nowrap">4.0 <span title="End-of-life">&#8224;</span><br>
                (1997&#8208;09)</td>
              <td headers="ie jscript3.1" class="nowrap">4.01 <span title="End-of-life">&#8224;</span><br>
              	(1997&#8208;11)</td>
              <td></td>
              <td headers="ie jscript5.0">5.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">1999&#8208;03</span>/
                <span class="date">2005&#8208;06</span>)</td>
              <td headers="ie jscript5.1" class="nowrap">5.01 <span title="End-of-life">&#8224;</span></td>
              <td headers="ie jscript5.5">5.5&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">2000&#8208;07</span>/
                <span class="date">2005&#8208;12</span>)</td>
              <td headers="ie jscript5.6">6.0 for <abbr title="Windows 95 and 98">Win9x</abbr>/NT/XP&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">2001&#8208;10</span>)</td>
              <td headers="ie jscript5.7.5730">7.0 for <abbr title="Windows">Win</abbr>XP+<br>
                (<span class="date">2006&#8208;10</span>)</td>
              <td headers="ie jscript5.7.17184">8.0 beta 1 for <abbr title="Windows">Win</abbr>XP SP2+<br>
                (<span class="date">2008&#8208;03</span>)</td>
              <td headers="ie jscript5.8">8.0 beta&nbsp;2 for <abbr title="Windows">Win</abbr>XP SP2+<br>
                (<span class="date">2008&#8208;08</span>)</td>
              <td colspan="3">&nbsp;</td>
              <td headers="ie jscript9.0"><span title="9.0.8112.16421">9.0</span> for Vista SP2+ / Server&nbsp;2008<br>
                (2011&#8208;03&#8208;14)</td>
              <td>&nbsp;</td>
              <td headers="ie jscript10.0">10 for Windows&nbsp;8
                (2012&#8208;08)</td>
              <td headers="ie jscript11.0">11.0.16518
                (2013&#8208;10)</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="20">Web Servers</th>
            </tr>
            <tr>
              <th scope="row" id="iis"><a href="http://microsoft.com/iis/">Microsoft Internet
              Information Server/Services</a></th>
              <td colspan="2"></td>
              <td headers="iis jscript3.0">4.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">1998/2002</span)></td>
              <td colspan="5"></td>
              <td headers="iis jscript5.6">5.1–6.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">2000/2005</span>)</td>
              <td headers="iis jscript5.7.5730 jscript5.7.17184" colspan="2">7.0<br>
                (<span class="date">2008</span>)</td>
              <td headers="iis jscript5.8">7.5<br>
                (<span class="date">2009</span>)</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="20">Operating Systems</th>
            </tr>
            <tr>
              <th scope="row" id="windows"><a href="http://microsoft.com/windows/">Microsoft Windows</a></th>
              <td></td>
              <td headers="windows jscript2.0">NT&nbsp;4.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">1996</span>)</td>
              <td colspan="4"></td>
              <td headers="windows jscript5.1">2000&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">2000&#8208;02</span>/
                <span class="date">2005&#8208;06</span>)</td>
              <td headers="windows jscript5.5"><abbr title="Millennium Edition">Me</abbr>&nbsp;<span
                title="End-of-life">&#8224;</span><br>
                (<span class="date">2000&#8208;09</span>/
                <span class="date">2005&#8208;12</span>)</td>
              <td headers="windows jscript5.6"><abbr title="eXPeriment^H^H^H^Hence ;-)">XP</abbr><br>
                (<span class="date">2001&#8208;10</span>)</td>
              <td headers="windows jscript5.7.5730 jscript5.7.17184" colspan="2">Vista<br>
                (<span class="date">2008&#8208;03</span>)</td>
              <td headers="windows jscript5.8">7<br>
                (<span class="date">2009&#8208;10</span>)</td>
              <td colspan="3">&nbsp;</td>
              <td headers="windows jscript9.0">7</td>
              <td>&nbsp;</td>
              <td headers="windows jscript10.0">8 (<span class="date">2012&#8208;10&#8208;26</span>)</td>
              <td headers="windows jscript11.0">8.1 (<span class="date">2013&#8208;10&#8208;17</span>)</td>
            </tr>
            <tr>
              <th scope="row" id="windows-server"><a href="http://microsoft.com/windowsserver2003/"
                     >Microsoft Windows Server</a></th>
              <td colspan="8"></td>
              <td headers="windows-server jscript5.6">2003<br>
                (<span class="date">2003&#8208;04</span>)</td>
              <td headers="windows-server jscript5.7.5730 jscript5.7.17184" colspan="2">2008<br>
                (<span class="date">2008&#8208;02</span>)</td>
              <td headers="windows-server jscript5.8">2008&nbsp;R2<br>
                (<span class="date">2009&#8208;09</span>)</td>
              <td colspan="2">&nbsp;</td>
              <td headers="windows-server jscript8.0">2008</td>
              <td>&nbsp;</td>
              <td headers="windows-server jscript.net10.0">2008&nbsp;R2</td>
            </tr>
          </tbody>
          <tbody>
            <tr class="header">
              <th scope="rowgroup" colspan="20"><abbr
                title="Integrated Development Environment"
              >IDE</abbr>s</th>
            </tr>
            <tr>
              <th scope="row" id="visual-studio"><a
                href="http://www.microsoft.com/visualstudio/eng/products/visual-studio-overview"
                >Microsoft Visual Studio</a></th>
              <td colspan="4"></td>
              <td headers="visual-studio jscript4.0">6.0&nbsp;<span title="End-of-life">&#8224;</span><br>
                (<span class="date">1998/2005</span>)</td>
              <td colspan="7"></td>
              <td headers="visual-studio jscript.net7.0">.NET&nbsp;7.0<br>(2002)</td>
              <td headers="visual-studio jscript.net7.1">.NET&nbsp;7.1<br>(2003)</td>
              <td headers="visual-studio jscript.net8.0">8.0–9.0<br>(2005/2008)</td>
              <td></td>
              <td headers="visual-studio jscript.net10.0">10.0<br>(2010&#8208;04&#8208;12)</td>
            </tr>
          </tbody>
        </table>