        <div>
          <h3><a name="opera" id="opera">Opera&nbsp;ECMAScript Version
            Information</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            Opera ECMAScript versions and the user agents that support
            them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>Opera&nbsp;ECMAScript&nbsp;3.60</th>
              <th>5.02</th>
              <th>6.06</th>
              <th>7.02</th>
              <th>8.0</th>
              <th>9.27</th>
              <th>9.52</th>
              <th>9.62</th>
              <th>9.64</th>
              <th>10.10</th>
              <th>10.50</th>
              <th>10.51</th>
              <th>10.54</th>
              <th>10.63</th>
              <th>11.50</th>
            </tr>
          </thead>
          <tbody>
            <tr class="header">
              <th colspan="16">Implementations</th>
            </tr>
            <tr>
              <td></td>
              <td colspan="3">Linear A</td>
              <td colspan="3">Linear B</td>
              <td colspan="4">Futhark</td>
              <td colspan="5">Carakan</td>
            </tr>
            <tr class="header">
              <th colspan="16">Layout Engines</th>
            </tr>
            <tr>
              <td></td>
              <td colspan="3">Elektra</td>
              <td colspan="2">Presto 1.0</td>
              <td>2.0</td>
              <td>2.1</td>
              <td colspan="2">2.1.1</td>
              <td>2.4</td>
              <td colspan="3">2.5</td>
              <td>2.6</td>
              <td>2.7</td>
            </tr>
            <tr class="header">
              <th colspan="16">Web Browsers</th>
            </tr>
            <tr>
              <th><a href="http://opera.com/">Opera Browser</a></th>
              <td>3.60&nbsp;<span title="End-of-life">&#8224;</span><br>
                (1999-05)</td>
              <td>5.02&nbsp;<span title="End-of-life">&#8224;</span><br>
              	(2000-12)</td>
              <td>6.06<br>
                (2001-11)</td>
              <td>7.02<br>
                (2003–2005)</td>
              <td>8.0<br>
                (2005–2008)</td>
              <td>9.27<br>
                (2008)</td>
              <td>9.52<br>
                (2008)</td>
              <td>9.62<br>
                (2008–2009)</td>
              <td>9.64<br>
                (2009)</td>
              <td>10.10<br>
                (2009–2010)</td>
              <td>10.50<br>
                (2010-03-02)</td>
              <td>10.51<br>
                (2010-03-22)</td>
              <td>10.54<br>
                (2010-06-21)</td>
              <td>10.63<br>
                (2010-10-12)</td>
              <td>11.50<br>
                (2011-06-28)</td>
            </tr>
          </tbody>
        </table>