        <div>
          <h3><a name="v8" id="v8">Google&nbsp;V8 Version
          Information</a></h3>

          <div><a href="#version-info">&#8593; Version information</a></div>
        </div>

        <table class="versions">
          <caption>
            V8 versions and the user agents that support them
          </caption>
          <thead>
            <tr>
              <th></th>
              <th>V8&nbsp;0.3</th>
              <th>0.4</th>
              <th>1.2</th>
              <th>1.3</th>
              <th>2.0</th>
              <th>2.1</th>
              <th>2.2</th>
              <th>2.3.11.22</th>
              <th>2.4.9.19</th>
              <th>2.5.9.6</th>
              <th>3.0.12.18</th>
              <th>3.1.4.0</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th><a href="http://www.google.com/chrome/">Google Chrome</a></th>
              <td>0.2–1.0<br>
                (2008-09&nbsp;<a
                href="http://en.wikipedia.org/wiki/Common_Era"
              ><abbr title="Common Era">CE</abbr></a>&#8212;2008-12)</td>
              <td>2.0<br>
                (2009-05)</td>
              <td>3.0<br>
                (2009-10)</td>
              <td>4.0.249<br>
                (2010-01-25)</td>
              <td>5.0.307<br>
                (2010-01-30)</td>
              <td>5.0.342<br>
                (2010-04-07)</td>
              <td>6.0.466.0<br>
                (2010-07-15)</td>
              <td>7.0.517<br>
                (2010-10-21)</td>
              <td>8.0.552<br>
                (2010-12-02)</td>
              <td>9.0.597<br>
                (2011-02-03)</td>
              <td>10.0.648<br>
                (2011-03-11)</td>
              <td>11.0.672<br>
                (2011-03-08)</td>
            </tr>
          </tbody>
        </table>