ppan
<div>
  <h3>
    <a name="v8" id="v8">Google&nbsp;V8 Version Information</a>
  </h3>

  <div>
    <a href="#version-info">&#8593; Version information</a>
  </div>
</div>

<table class="versions">
  <caption>V8 versions and the user agents that support them</caption>
  <thead>
    <tr>
      <th></th>
      <th>V8&nbsp;0.3</th>
      <th>0.4</th>
      <th>1.2</th>
      <th>1.3</th>
      <th>2.0</th>
      <th>2.1</th>
      <th>2.2</th>
      <th title="2.3.11.22">2.3</th>
      <th title="2.4.9.19">2.4</th>
      <th title="2.5.9.6">2.5</th>
      <th title="3.0.12.18 –&nbsp;3.0.12.30">3.0</th>
      <th title="3.1.4.0 –&nbsp;3.1.8.16">3.1</th>
      <th title="3.2.10.21">3.2</th>
      <th title="3.3.10.30">3.3</th>
      <th title="3.4.14.21">3.4</th>
      <th title="3.5.10.24">3.5</th>
      <th title="3.6.6.19">3.6</th>
      <th title="3.7.12.29">3.7</th>
      <th title="3.8.9.19">3.8</th>
      <th title="3.9.24.7">3.9</th>
      <th title="3.10.6.0">3.10</th>
      <th title="3.11.10.6">3.11</th>
      <th title="3.12.19.4">3.12</th>
      <th title="3.13.7.1">3.13</th>
      <th title="3.14.5.0">3.14</th>
      <th title="3.15.11.5">3.15</th>
      <th title="3.16.14.9">3.16</th>
      <th title="3.17.6.14">3.17</th>
      <th title="3.18.5.8 –&nbsp;3.18.5.14">3.18</th>
      <th title="3.19.18.19">3.19</th>
      <th title="3.20.17.13">3.20</th>
      <th title="3.21.18.7">3.21</th>
      <th title="3.22.24.10">3.22</th>
      <th title="3.23.17.13">3.23</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th><a href="http://www.google.com/chrome/">Google Chrome</a></th>
      <td>0.2–1.0<br> (<span title="2008-09 &#8212;&nbsp;2008-12">2008</span>&nbsp;<a
        href="http://en.wikipedia.org/wiki/Common_Era"
      ><abbr title="Common Era">CE</abbr></a>)
      </td>
      <td>2.0<br> (<span title="2009-05">2009</span>)
      </td>
      <td>3.0<br> (<span title="2009-10">2009</span>)
      </td>
      <td>4.0.249 –&nbsp;4.1.249<br>
        (<span title="2010-01-25 –&nbsp;2010-03-17">2010</span>)
      </td>
      <td>5.0.307<br>
        (<span title="2010-01-30">2010</span>)
      </td>
      <td>5.0.342 –&nbsp;5.0.375<br>
        (<span title="2010-04-07 –&nbsp;2010-05-21">2010</span>)
      </td>
      <td><span title="6.0.466 –&nbsp;6.0.472">6</span><br>
        (<span title="2010-07-15 –&nbsp;2010-09-02">2010</span>)
      </td>
      <td><span title="7.0.517">7</span><br>
        (<span title="2010-10-21">2010</span>)
      </td>
      <td><span title="8.0.552">8</span><br>
        (<span title="2010-12-02">2010</span>)
      </td>
      <td><span title="9.0.597">9</span><br>
        (<span title="2011-02-03">2011</span>)
      </td>
      <td><span title="10.0.648">10</span><br>
        (<span title="2011-03-11">2011</span>)
      </td>
      <td><span title="11.0.672">11</span><br>
        (<span title="2011-03-08">2011</span>)
      </td>
      <td><span title="12.0.742">12</span><br>
        (<span title="2011-06-07">2011</span>)
      </td>
      <td><span title="13.0.782">13</span><br>
        (<span title="2011-08-02">2011</span>)
      </td>
      <td><span title="14.0.835">14</span><br>
        (<span title="2011-09-16">2011</span>)
      </td>
      <td><span title="15.0.874">15</span><br>
        (<span title="2011-10-25">2011</span>)
      </td>
      <td><span title="16.0.912">16</span><br>
        (<span title="2011-12-13">2011</span>)
      </td>
      <td><span title="17.0.963">17</span><br>
        (<span title="2012-02-08">2012</span>)
      </td>
      <td><span title="18.0.1025 –&nbsp;18.0.1026">18</span>
        (<span title="2012-03-28 –&nbsp;2012-09-26">2012</span>)
      </td>
      <td><span title="19.0.1084">19</span> (<span title="2012-05-15 –&nbsp;2012-06-28">2012</span>)</td>
      <td><span title="20.0.1132">20</span> (<span title="2012-06-26">2012</span>)</td>
      <td><span title="21.0.1180">21</span> (<span title="2012-07-31 –&nbsp;2012-08-22">2012</span>)</td>
      <td><span title="22.0.1229">22</span> (<span title="2012-09-25">2012</span>)</td>
      <td><span title="23.0.1271">23</span> (<span title="2012-11-06 –&nbsp;2012-11-28">2012</span>)</td>
      <td><span title="24.0.1312">24</span> (<span title="2013-01-10">2013</span>)</td>
      <td><span title="25.0.1364">25</span> (<span title="2013-02-21 –&nbsp;2013-03-04">2013</span>)</td>
      <td><span title="26.0.1410">26</span> (<span title="2013-03-26 –&nbsp;2013-04-09">2013</span>)</td>
      <td><span title="27.0.1453">27</span> (<span title="2013-05-21 –&nbsp;2013-06-03">2013</span>)</td>
      <td><span title="28.0.1500.95">28</span> (<span title="2013-06-17 –&nbsp;2013-07-17">2013</span>)</td>
      <td><span title="29.0.1547">29</span> (<span title="2013-08-20 –&nbsp;2013-09-12">2013</span>)</td>
      <td><span title="30.0.1599">30</span> (<span title="2013-09-18 –&nbsp;2013-10-02">2013</span>)</td>
      <td><span title="31.0.1650">31</span> (<span title="2013-11-12 –&nbsp;2013-11-20">2013</span>)</td>
      <td><span title="32.0.1700">32</span> (<span title="2014-01-14 –&nbsp;2014-01-27">2014-01</span>)</td>
      <td><span title="33.0.1750">33</span> (<span title="2014-02-18 –&nbsp;2014-02-26">2014-02</span>)</td>
    </tr>
  </tbody>
</table>