<?php $feature = $this->feature; ?>
    <h2><?php if ($feature->id) { ?>Edit<?php } else { ?>Add<?php } ?> Feature</h2>
    <form action="<?php echo $this->escape($this->getURL('feature', 'save')); ?>" method="POST"
          style="width: 100%">
      <input type="hidden" name="id" value="<?php echo $feature->id; ?>">
      <table style="width: 100%">
        <tr>
          <th>Title</th>
          <td><input name="title" style="width: 99%"
                     value="<?php echo $this->escape($feature->title); ?>"></td>
        </tr>
        <tr>
          <th style="vertical-align: top">Code</th>
          <td><textarea name="code" cols="80" rows="4" style="width: 99%"
                        ><?php echo $this->escape($feature->code); ?></textarea></td>
        </tr>
        <tr>
          <th>Edition</th>
          <td><input name="edition" size="1"
                     value="<?php echo $this->escape($feature->edition); ?>"></td>
        </tr>
        <tr>
          <th>Section</th>
          <td><input name="section" size="15"
                     value="<?php echo $this->escape($feature->section); ?>"></td>
        </tr>
        <tr>
          <th>Section URN</th>
          <td><input name="section_urn" size="15"
                     value="<?php echo $this->escape($feature->section_urn); ?>"></td>
        </tr>

        <tr>
          <th style="vertical-align: top">Testcases</th>
          <td><script type="text/javascript">
              function deleteTestcase(deleteButton, id)
              {
                var prefixes = ["title", "code"];
                for (var i = prefixes.length; i--;)
                {
                  var prefix = prefixes[i];
                  var control = deleteButton.form.elements["testcase_" + prefix + id];
                  control.parentNode.removeChild(control);
                }
                
                deleteButton.parentNode.removeChild(deleteButton);
              }
            </script>
<?php
  $testcases = $feature->testcases;
  if (is_array($testcases))
  {
    foreach ($testcases as $key => $testcase)
    {
?>
            <input name="testcase_title[]" id="testcase_title<?php echo $key; ?>" type="text"
                   value="<?php echo $this->escape($testcase->title); ?>"
                   style="width: 99%">
            <textarea name="testcase_code[]" id="testcase_code<?php echo $key; ?>"  cols="80" rows="4"
                      style="width: 99%"><?php echo $this->escape($testcase->code); ?></textarea>
            <button type="button" style="float: right"
                    onclick="deleteTestcase(this, <?php echo $key; ?>)">Delete</button>
<?php
    }
  }
?>
            <script type="text/javascript">
              function addTestcase(addButton)
              {
                var input = document.createElement("input");
                input.type = "text";
                input.name = "testcase_title[]";
                var numTestcases = [].concat(addButton.form.elements["testcase_title[]"] || []).length;
                input.id = "testcase_title" + numTestcases;
                input.value = "";
                input.style.width = "99%";

                var textarea = document.createElement("textarea");
                textarea.name = "testcase_code[]";
                textarea.id = "testcase_code" + numTestcases;
                textarea.cols = 80;
                textarea.rows = 4;
                textarea.style.width = "99%";

                var button = document.createElement("button");
                button.type = "button";

                if (button.type != "button")
                {
                  button.setAttribute("type", "button");
                }

                button.onclick = (function (id) {
                  return function () {
                    deleteTestcase(this, id);
                  };
                }(numTestcases));
                                
                if (typeof button.style.cssFloat != "undefined")
                {
                  button.style.cssFloat = "right";
                }
                else if (typeof button.style.styleFloat != "undefined")
                {
                  button.style.styleFloat = "right";
                }

                button.appendChild(document.createTextNode("Delete"));

                var parentNode = addButton.parentNode;
                parentNode.insertBefore(input, addButton);
                parentNode.insertBefore(textarea, addButton);
                parentNode.insertBefore(button, addButton);
              }
            </script>
            <button type="button" name="testcase_action" value="add" style="float: left"
                    onclick="addTestcase(this)">Add</button>
          </td>
        </tr>
      </table>
      <button type="submit">Save</button>
      <button type="submit" name="cancel" value="1" class="negative"
              onclick="history.back(); return false">Cancel</button>
    </form>