<?php $feature = $this->feature; ?>
    <h2><?php if ($feature->id) { ?>Edit<?php } else { ?>Add<?php } ?> Feature</h2>
    <form action="<?php echo $this->escape($this->getURL('feature', 'save')); ?>" method="POST"
          style="width: 100%">
      <input type="hidden" name="id" value="<?php echo $feature->id; ?>">
      <table style="width: 100%">
        <tr>
          <th>Title</th>
          <td><input name="title" style="width: 99%"
                     value="<?php echo $this->escape($feature->title); ?>"></td>
        </tr>
        <tr>
          <th style="vertical-align: top">Code</th>
          <td><textarea name="code" cols="80" rows="4" style="width: 99%"
                        ><?php echo $this->escape($feature->code); ?></textarea></td>
        </tr>
        <tr>
          <th>Edition</th>
          <td><input name="edition" size="1"
                     value="<?php echo $this->escape($feature->edition); ?>"></td>
        </tr>
        <tr>
          <th>Section</th>
          <td><input name="section" size="15"
                     value="<?php echo $this->escape($feature->section); ?>"></td>
        </tr>
        <tr>
          <th>Section URN</th>
          <td><input name="section_urn" size="15"
                     value="<?php echo $this->escape($feature->section_urn); ?>"></td>
        </tr>

        <tr>
          <th style="vertical-align: top">Testcases</th>
          <td><script type="text/javascript">
              function deleteTestcase(deleteButton, id)
              {
                var prefixes = ["title", "code"];
                for (var i = prefixes.length; i--;)
                {
                  var prefix = prefixes[i];
                  var control = deleteButton.form.elements["testcase_" + prefix + id];
                  control.parentNode.removeChild(control);

                }

                var label = document.getElementById("testcase_quoted" + id);
                label.parentNode.removeChild(label);
                
                deleteButton.parentNode.removeChild(deleteButton);
              }
            </script>
<?php
  $testcases = $feature->testcases;
  if (is_array($testcases))
  {
    foreach ($testcases as $key => $testcase)
    {
?>
            <input name="testcase_title[]" id="testcase_title<?php echo $key; ?>" type="text"
                   value="<?php echo $this->escape($testcase->title); ?>"
                   style="width: 99%">
            <textarea name="testcase_code[]" id="testcase_code<?php echo $key; ?>"  cols="80" rows="4"
                      style="width: 99%"><?php echo $this->escape($testcase->code); ?></textarea>
            <label style="float: left" id="testcase_quoted<?php echo $key; ?>">
              <input type="checkbox" name="testcase_quoted[]"
                     value="1" <?php if ($testcase->quoted) { ?>checked<?php }; ?>>
              Surround with double-quotes</label>
            <button type="button" class="delete" style="float: right; margin-bottom: 1em"
                    onclick="deleteTestcase(this, <?php echo $key; ?>)">Delete</button>
<?php
    }
  }
?>
            <script type="text/javascript">
              var _createElement = jsx.dom.createElementFromObj;
              function addTestcase(addButton)
              {
                var numTestcases = (addButton.form.elements["testcase_title[]"] || []).length;
                var input = _createElement({
                  type: "input",
                  properties: {
                    type: "text",
                    name: "testcase_title[]",
                    id: "testcase_title" + numTestcases,
                    value: "",
                    style: {
                      width: "99%"
                    }
                  }
                });

                var textarea = _createElement({
                  type: "textarea",
                  properties: {
                    name: "testcase_code[]",
                    id: "testcase_code" + numTestcases,
                    cols: 80,
                    rows: 4,
                    style: {
                      width: "99%"
                    }
                  }
                });

                var label = _createElement({
                  type: "label",
                  properties: {
                    id: "testcase_quoted" + numTestcases,
                    style: {
                      "float": "left",
                    }
                  },
                  childNodes: [
                    {
                      type: "input",
                      properties: {
                        type: "checkbox",
                        name: "testcase_quoted[]",
                        value: "1",
                      }
                    },
                    "Surround with double-quotes"
                  ]
                });
                
                var button = _createElement({
                  type: "button",
                  properties: {
                    type: "button",
                    className: "delete",
                    onclick: (function (id) {
                      return function () {
                        deleteTestcase(this, id);
                      };
                    }(numTestcases)),
                    style: {
                      "float": "right",
                      marginBottom: "1em"
                    }
                  },
                  childNodes: [
                    "Delete"
                  ]
                });

                if (button.type != "button")
                {
                  button.setAttribute("type", "button");
                }

                var parentNode = addButton.parentNode;
                parentNode.insertBefore(input, addButton);
                parentNode.insertBefore(textarea, addButton);
                parentNode.insertBefore(label, addButton);
                parentNode.insertBefore(button, addButton);
              }
            </script>
            <button type="button" name="testcase_action" value="add"
                    class="add" style="float: left; clear: both"
                    onclick="addTestcase(this)">Add</button>
          </td>
        </tr>
        <tr>
          <td>
            <button type="submit" class="positive" style="float: left">Save</button>
            <button type="submit" name="cancel" value="1" class="negative" style="float: right"
                    onclick="history.back(); return false">Cancel</button>
          </td>
          <td>
            <button type="button" value="1" class="negative" style="float: right"
                    onclick="window.location.reload(true)">Reset</button>
          </td>
        </tr>
      </table>
    </form>
    <div style="clear: both"><!--  --></div>