<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html<?php
      if ($this->encoding)
      {
        echo "; charset= {$this->encoding}";
      }
      ?>">
    <meta http-equiv="Content-Script-Type" content="text/javascript">
    <meta http-equiv="Content-Style-Type" content="text/css">
    
    <title>ECMAScript Support Matrix - Database Version</title>
    
    <meta name="DCTERMS.alternative" content="ES Matrix">
    <meta name="DCTERMS.audience" content="Web developers">
    <meta name="DCTERMS.available" content="2009-12-15T04:06:35+00:00">
    
    <meta name="DCTERMS.created" content="2005-11-29T00:42:12+01:00">

    <link rel="stylesheet" href="/styles/tooltip.css" type="text/css">
    <link rel="stylesheet" href="../../style.css" type="text/css">
    <link rel="stylesheet" href="style.css" type="text/css">
    <link rel="stylesheet" href="not-ns4.css" type="text/css" media="all">
    <link rel="alternate stylesheet" href="ct.css" type="text/css" title="c't">
    <!--[if lt IE 7]>
      <style type="text/css">
        /* IE 6 does not support position:fixed */
        #header {
          margin-top: 0;
        }
        
        #toc {
          margin-top: 1em;
          padding: 0;
          height: auto;
          border-style: solid none none none;
        }
      </style>
    <![endif]-->
    
    <script type="text/javascript">
      var jsx = {
        options: {
          emulate: false
        }
      };
    </script>
    <script type="text/javascript"
            src="../../builder?<?php
              if ($_SERVER['HTTP_HOST'] === 'localhost')
              {
                ?>debug=1&verbose=1&<?php
              }
              ?>src=test/es-matrix/application/scripts/object,test/debug,dom"></script>
  </head>
  
  <body onload="synhl()">
    <div id="header">
      <h1><a name="top" id="top">ECMAScript Support Matrix</a></h1>
    </div>
    
    <?php echo $this->getContent(); ?>
  </body>
</html>