<?php
//phpinfo();
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html<?php
      if ($this->encoding)
      {
        echo "; charset={$this->encoding}";
      }
      ?>">
<?php /*
    <meta http-equiv="Content-Script-Type" content="text/javascript">
    <meta http-equiv="Content-Style-Type" content="text/css">
*/ ?>
    <title>ECMAScript Support Matrix 2 (under construction)</title>
    
    <meta name="DCTERMS.alternative" content="ES Matrix">
    <meta name="DCTERMS.audience" content="Web developers">
    <meta name="DCTERMS.available" content="2009-12-15T04:06:35+00:00">
    
    <meta name="DCTERMS.created" content="2005-11-29T00:42:12+01:00">

    <link rel="stylesheet" href="/styles/tooltip.css" type="text/css">
    <link rel="stylesheet" href="../../style.css" type="text/css">
    <link rel="stylesheet" href="style.css" type="text/css">
    <link rel="stylesheet" href="not-ns4.css" type="text/css" media="all">
    <link rel="alternate stylesheet" href="ct.css" type="text/css" title="c't">
    <!--[if lt IE 7]>
      <style type="text/css">
        /* IE 6 does not support position:fixed */
        #header {
          margin-top: 0;
        }
        
        #toc {
          margin-top: 1em;
          padding: 0;
          height: auto;
          border-style: solid none none none;
        }
      </style>
    <![endif]-->
    
    <script type="text/javascript">
      var jsx = new Object();
      jsx.options = new Object();
      jsx.options.emulate = false;
    </script>
    <!-- FIXME: dom.js interferes with emulate = false  -->
    <script type="text/javascript" src="application/scripts/object/object-compat.js"></script>
    <script type="text/javascript"
            src="../../builder.php?<?php
              if ($_SERVER['HTTP_HOST'] === 'localhost')
              {
                ?>debug=1&amp;verbose=1&amp;<?php
              }
              ?>src=test/es-matrix/application/scripts/es,dom/xpath,test/es-matrix/application/scripts/debug,http,string/hyphenation,dom,dom/events,dom/widgets"
            ></script>
    <script type="text/javascript" src="table.js"></script>
    <script type="text/javascript" src="application/scripts/es-matrix.js"></script>
  </head>
  
  <body onload="body_load()">
    <header>
      <div id="header" style="margin-bottom: 1em; padding-bottom: 1em; border-bottom: 1px solid black">
        <h1><a name="top" id="top">ECMAScript Support Matrix</a></h1>
        <p class="subtitle">There is no javascript.</p>
  
        <p style="text-align: left">
          Version 2 <em>(under construction)</em><br>
          Copyright &copy; 2005&#8211;<?php global $modi; echo gmdate('Y', $modi); ?>
            <a href="/">Thomas Lahn</a>
            &lt;<a href="<?php echo randomEsc('mailto:js@PointedEars.de'); ?>"
            ><?php echo randomEsc('js@PointedEars.de'); ?></a>&gt;
            (<a href="#contributors">contributors</a>)</p>
  
        <div>
          <p style="margin-bottom: 0; text-align: left">
            Last&nbsp;modified:
            <?php echo gmdate('Y-m-d\TH:i:s+00:00', $modi); ?>
          </p>
      
          <ul class="horizontal">
            <li><a
              href="http://PointedEars.de/websvn/log.php?repname=es-matrix&amp;path=%2Ftrunk%2F&amp;isdir=1&amp;showchanges=1"
            >Change&nbsp;log</a></li>
            <li><a
              href="http://PointedEars.de/websvn/listing.php?repname=es-matrix&amp;path=%2Ftrunk%2F"
              title="Subversion repository browser"
            >SVN</a></li>
          </ul>
        </div>
      
        <p style="clear: left; text-align: left">
          Available online at <a
            href="<?php
                     $s = 'http://PointedEars.de/scripts/test/es-matrix/index-db';
                     echo $s;
                   ?>"
          ><?php echo $s; ?></a>
        </p>
        
        <div><a href="#toc">Table of contents</a></div>
        
<?php
  if ($_SERVER['QUERY_STRING'] == 'redir')
  {
?>
        <p><strong>You have been redirected here because the URI that was used
          to access this resource is obsolete, and may stop working in the future.
          Please update your bookmarks using the link/URI above. If you followed
          a link from another site, please notify its webmaster about
          the change.</strong></p>
<?php
  }
?>
      </div>

      <nav id="toc">
        <h2>Table of contents</h2>
        
        <div><a href="#top">&#8593; Top of document</a></div>
        
        <ul>
          <li><a href="#abstract">Abstract</a></li>
          <li><a href="#foreword">Foreword and rationale</a></li>
          <li><a href="#features">Language features</a></li>
          <li><a href="#version-info">Version information</a>
            <ul>
              <li><a href="#javascript">Netscape/Mozilla.org JavaScript</a></li>
              <li><a href="#jscript">Microsoft JScript</a></li>
              <li><a href="#v8">Google V8</a></li>
              <li><a href="#jsc">Apple JavaScriptCore</a></li>
              <li><a href="#opera">Opera ECMAScript</a></li>
              <li><a href="#actionscript">Adobe ActionScript</a></li>
              <li><a href="#ecmascript">ECMAScript compatibility</a></li>
              <li><a href="#timeline">Timeline</a></li>
            </ul></li>
          <li><a href="#contributors">List of contributors</a></li>
        </ul>
      </nav>
    </header>
    
<?php echo $this->getContent(); ?>
  </body>
</html>
